import type { Locale } from './i18n'

const en = {
  forecast: 'Forecast',
  crossplayOn: 'Crossplay on',
  crossplayOff: 'Crossplay off',
  crossplayUnavailable: 'Unavailable on Switch',
  shownRanges: 'Displayed ranges',
  allRanges: 'All ranges',
  hourlyLive: 'Hourly data',
  hourlyUnavailable: 'Hourly data has not been collected for this market yet',
  loadingHourly: 'Loading hourly ranges…',
  hourlyPartial: 'Some hourly markets are still waiting for collection.',
  range1h: '1h',
  range4h: '4h',
  range12h: '12h',
  range24h: '24h',
  range7d: '7d',
  range30d: '30d',
  range90d: '90d',
  range180d: '180d',
  trendUp: 'Expected upward tendency',
  trendDown: 'Expected downward tendency',
  trendFlat: 'No clear tendency',
  noHistory: 'No history',
  variant: 'Variant',
  chooseVariant: 'Choose a market variant',
  rank: 'Rank',
  rankFilter: 'Item ranks',
  rankBase: 'Rank 0 / no rank',
  rankAll: 'All available ranks',
  canonical: 'daily analytics',
  hourlyOnlyRank: 'hourly data only',
  prime: 'Prime items',
  forecastHint: 'Forecast score uses the longest displayed daily range; the arrow is the consensus across all displayed ranges. This is analytics, not a guarantee.',
  catalogSummary: 'catalog items',
  seriesSummary: 'market series',
  loadingRanges: 'Loading additional ranges…',
  rangesError: 'Some additional ranges could not be loaded.',
  chooseRanges: 'Choose columns',
  itemImage: 'Item image',
  dataUnavailable: 'Data unavailable',
  close: 'Close',
  typicalPrice: 'Typical price',
  typicalPriceHint: 'The middle daily price: half of the available days were cheaper and half were more expensive.',
  lowerPrice: 'Lower price range',
  lowerPriceHint: 'Only about 25% of available daily prices were at or below this value.',
  upperPrice: 'Upper price range',
  upperPriceHint: 'Only about 25% of available daily prices were above this value.',
  priceFluctuation: 'Price fluctuation',
  priceFluctuationHint: 'How strongly the price varied around its average. A smaller percentage means a more stable market.',
  openOnWfm: 'Open on WFM',
  wfmItemHint: 'Open this item on Warframe Market'
} as const

export type ExtraText = Record<keyof typeof en, string>

const ru: ExtraText = {
  forecast: 'Прогноз',
  crossplayOn: 'Кроссплей включён',
  crossplayOff: 'Кроссплей выключен',
  crossplayUnavailable: 'Недоступен на Switch',
  shownRanges: 'Показываемые диапазоны',
  allRanges: 'Все диапазоны',
  hourlyLive: 'Почасовые данные',
  hourlyUnavailable: 'Почасовые данные этого рынка ещё не собраны',
  loadingHourly: 'Загрузка почасовых диапазонов…',
  hourlyPartial: 'Часть почасовых рынков ещё ожидает первого сбора.',
  range1h: '1ч',
  range4h: '4ч',
  range12h: '12ч',
  range24h: '24ч',
  range7d: '7д',
  range30d: '30д',
  range90d: '90д',
  range180d: '180д',
  trendUp: 'Ожидается тенденция вверх',
  trendDown: 'Ожидается тенденция вниз',
  trendFlat: 'Явной тенденции нет',
  noHistory: 'Нет истории',
  variant: 'Вариант',
  chooseVariant: 'Выберите вариант рынка',
  rank: 'Ранг',
  rankFilter: 'Ранги предметов',
  rankBase: 'Ранг 0 / без ранга',
  rankAll: 'Все доступные ранги',
  canonical: 'daily-аналитика',
  hourlyOnlyRank: 'только hourly-данные',
  prime: 'Прайм предметы',
  forecastHint: 'Оценка прогноза берётся из самого длинного показанного daily-диапазона; стрелка показывает общую тенденцию всех видимых диапазонов. Это аналитика, а не гарантия.',
  catalogSummary: 'предметов каталога',
  seriesSummary: 'рыночных серий',
  loadingRanges: 'Загрузка дополнительных диапазонов…',
  rangesError: 'Часть дополнительных диапазонов не загрузилась.',
  chooseRanges: 'Выбрать столбцы',
  itemImage: 'Изображение предмета',
  dataUnavailable: 'Данные недоступны',
  close: 'Закрыть',
  typicalPrice: 'Типичная цена',
  typicalPriceHint: 'Центральная дневная цена: половину доступных дней предмет стоил дешевле, половину — дороже.',
  lowerPrice: 'Нижняя граница',
  lowerPriceHint: 'Только примерно в 25% доступных дней цена была не выше этого значения.',
  upperPrice: 'Верхняя граница',
  upperPriceHint: 'Только примерно в 25% доступных дней цена была выше этого значения.',
  priceFluctuation: 'Колебания цены',
  priceFluctuationHint: 'Насколько сильно менялась цена относительно среднего. Чем меньше процент, тем стабильнее рынок.',
  openOnWfm: 'Открыть на WFM',
  wfmItemHint: 'Открыть страницу этого предмета на Warframe Market'
}

export const getExtraText = (locale: Locale): ExtraText => locale === 'ru' ? ru : en
