import type { Locale } from './i18n'

const en = {
  forecast: 'Forecast',
  marketSettings: 'Market settings',
  crossplayOn: 'Crossplay on',
  crossplayOff: 'Crossplay off',
  platformData: 'Platform dataset',
  crossplayNotice: 'Crossplay is saved as a separate preference. Daily v3 data is still platform-specific and is not merged.',
  shownRanges: 'Displayed ranges',
  allRanges: 'All ranges',
  hourlyPending: 'Hourly collection is not connected yet',
  hourlyNote: '1h, 4h and 12h are ready in the interface, but stay empty until the 48-hour updater is connected.',
  range1h: '1h',
  range4h: '4h',
  range12h: '12h',
  range24h: '24h',
  range7d: '7d',
  range30d: '30d',
  range90d: '90d',
  range180d: '180d',
  trendUp: 'Expected upward tendency',
  trendDown: 'Expected downward tendency',
  trendFlat: 'No clear tendency',
  noHistory: 'No history',
  variant: 'Variant',
  chooseVariant: 'Choose a market variant',
  rank: 'Rank',
  prime: 'Prime items',
  forecastHint: 'Forecast icon and expected direction. This is analytics, not a guarantee.',
  catalogSummary: 'catalog items',
  seriesSummary: 'market series',
  loadingRanges: 'Loading additional ranges…',
  rangesError: 'Some additional ranges could not be loaded.',
  chooseRanges: 'Choose columns',
  itemImage: 'Item image',
  dataUnavailable: 'Data unavailable',
  close: 'Close'
} as const

export type ExtraText = Record<keyof typeof en, string>

const ru: ExtraText = {
  forecast: 'Прогноз',
  marketSettings: 'Настройки рынка',
  crossplayOn: 'Кроссплей включён',
  crossplayOff: 'Кроссплей выключен',
  platformData: 'Данные платформы',
  crossplayNotice: 'Кроссплей сохраняется как отдельная настройка. Daily v3 пока остаётся раздельным по платформам и не объединяется.',
  shownRanges: 'Показываемые диапазоны',
  allRanges: 'Все диапазоны',
  hourlyPending: 'Почасовой сбор ещё не подключён',
  hourlyNote: 'Интервалы 1ч, 4ч и 12ч уже есть в интерфейсе, но останутся пустыми до подключения 48-часового updater.',
  range1h: '1ч',
  range4h: '4ч',
  range12h: '12ч',
  range24h: '24ч',
  range7d: '7д',
  range30d: '30д',
  range90d: '90д',
  range180d: '180д',
  trendUp: 'Ожидается тенденция вверх',
  trendDown: 'Ожидается тенденция вниз',
  trendFlat: 'Явной тенденции нет',
  noHistory: 'Нет истории',
  variant: 'Вариант',
  chooseVariant: 'Выберите вариант рынка',
  rank: 'Ранг',
  prime: 'Прайм предметы',
  forecastHint: 'Иконка прогноза и предполагаемое направление. Это аналитика, а не гарантия.',
  catalogSummary: 'предметов каталога',
  seriesSummary: 'рыночных серий',
  loadingRanges: 'Загрузка дополнительных диапазонов…',
  rangesError: 'Часть дополнительных диапазонов не загрузилась.',
  chooseRanges: 'Выбрать столбцы',
  itemImage: 'Изображение предмета',
  dataUnavailable: 'Данные недоступны',
  close: 'Закрыть'
}

export const getExtraText = (locale: Locale): ExtraText => locale === 'ru' ? ru : en
