import type { Locale } from './i18n'

const en = {
  forecast: 'Forecast',
  crossplayOn: 'Crossplay on',
  crossplayOff: 'Crossplay off',
  crossplayUnavailable: 'Unavailable on Switch',
  shownRanges: 'Displayed ranges',
  allRanges: 'All ranges',
  hourlyLive: 'Hourly data',
  hourlyUnavailable: 'Hourly data has not been collected for this market yet',
  loadingHourly: 'Loading hourly ranges…',
  hourlyPartial: 'Some hourly markets are still waiting for collection.',
  range1h: '1h',
  range4h: '4h',
  range12h: '12h',
  range24h: '24h',
  range7d: '7d',
  range30d: '30d',
  range90d: '90d',
  range180d: '180d',
  trendUp: 'Expected upward tendency',
  trendDown: 'Expected downward tendency',
  trendFlat: 'No clear tendency',
  noHistory: 'No history',
  variant: 'Variant',
  chooseVariant: 'Choose a market variant',
  rank: 'Rank',
  rankFilter: 'Item ranks',
  rankBase: 'Rank 0 / no rank',
  rankAll: 'All available ranks',
  canonical: 'daily analytics',
  hourlyOnlyRank: 'hourly data only',
  prime: 'Prime items',
  forecastHint: 'Forecast score uses the longest displayed daily range; the arrow is the consensus across all displayed ranges. This is analytics, not a guarantee.',
  catalogSummary: 'catalog items',
  seriesSummary: 'market series',
  loadingRanges: 'Loading additional ranges…',
  rangesError: 'Some additional ranges could not be loaded.',
  chooseRanges: 'Choose columns',
  itemImage: 'Item image',
  dataUnavailable: 'Data unavailable',
  close: 'Close',
  typicalPrice: 'Typical price',
  typicalPriceHint: 'The middle daily price: half of the available days were cheaper and half were more expensive.',
  lowerPrice: 'Lower price range',
  lowerPriceHint: 'Only about 25% of available daily prices were at or below this value.',
  upperPrice: 'Upper price range',
  upperPriceHint: 'Only about 25% of available daily prices were above this value.',
  priceFluctuation: 'Price fluctuation',
  priceFluctuationHint: 'How strongly the price varied around its average. A smaller percentage means a more stable market.',
  openOnWfm: 'Open on WFM',
  wfmItemHint: 'Open this item on Warframe Market',
  specialFilter: 'Special filter',
  currentBaro: 'Baro inventory',
  currentBaroHint: "Show tradable items in Baro Ki'Teer's active inventory",
  latestBaroHint: "Baro Ki'Teer has left. Show tradable items from his latest completed inventory",
  currentBaroEmpty: "No tradable items from Baro Ki'Teer's latest inventory have been matched yet",
  currentResurgence: 'Current Prime Resurgence',
  currentResurgenceHint: 'Show all tradable items and parts from the current Prime Resurgence rotation, excluding Burston, Braton, Fang and Lex Prime families',
  currentResurgenceEmpty: 'No tradable items from the current Prime Resurgence rotation have been matched yet',
  tableColumns: 'Table columns',
  chooseTableColumns: 'Choose table columns',
  tableSettings: 'Table display',
  chooseTableSettings: 'Choose ranges and columns',
  priceChangeColumns: 'Price changes',
  otherColumns: 'Analytics',
  salesColumns: 'Sales intervals',
  potentialColumn: 'Potential',
  scoreColumn: 'Score',
  forecastColumn: 'Forecast',
  sales: 'Sales'
} as const

export type ExtraText = Record<keyof typeof en, string>

const ru: ExtraText = {
  forecast: 'Прогноз',
  crossplayOn: 'Кроссплей включён',
  crossplayOff: 'Кроссплей выключен',
  crossplayUnavailable: 'Недоступен на Switch',
  shownRanges: 'Показываемые диапазоны',
  allRanges: 'Все диапазоны',
  hourlyLive: 'Почасовые данные',
  hourlyUnavailable: 'Почасовые данные этого рынка ещё не собраны',
  loadingHourly: 'Загрузка почасовых диапазонов…',
  hourlyPartial: 'Часть почасовых рынков ещё ожидает первого сбора.',
  range1h: '1ч',
  range4h: '4ч',
  range12h: '12ч',
  range24h: '24ч',
  range7d: '7д',
  range30d: '30д',
  range90d: '90д',
  range180d: '180д',
  trendUp: 'Ожидается тенденция вверх',
  trendDown: 'Ожидается тенденция вниз',
  trendFlat: 'Явной тенденции нет',
  noHistory: 'Нет истории',
  variant: 'Вариант',
  chooseVariant: 'Выберите вариант рынка',
  rank: 'Ранг',
  rankFilter: 'Ранги предметов',
  rankBase: 'Ранг 0 / без ранга',
  rankAll: 'Все доступные ранги',
  canonical: 'daily-аналитика',
  hourlyOnlyRank: 'только hourly-данные',
  prime: 'Прайм предметы',
  forecastHint: 'Оценка прогноза берётся из самого длинного показанного daily-диапазона; стрелка показывает общую тенденцию всех видимых диапазонов. Это аналитика, а не гарантия.',
  catalogSummary: 'предметов каталога',
  seriesSummary: 'рыночных серий',
  loadingRanges: 'Загрузка дополнительных диапазонов…',
  rangesError: 'Часть дополнительных диапазонов не загрузилась.',
  chooseRanges: 'Выбрать столбцы',
  itemImage: 'Изображение предмета',
  dataUnavailable: 'Данные недоступны',
  close: 'Закрыть',
  typicalPrice: 'Типичная цена',
  typicalPriceHint: 'Центральная дневная цена: половину доступных дней предмет стоил дешевле, половину — дороже.',
  lowerPrice: 'Нижняя граница',
  lowerPriceHint: 'Только примерно в 25% доступных дней цена была не выше этого значения.',
  upperPrice: 'Верхняя граница',
  upperPriceHint: 'Только примерно в 25% доступных дней цена была выше этого значения.',
  priceFluctuation: 'Колебания цены',
  priceFluctuationHint: 'Насколько сильно менялась цена относительно среднего. Чем меньше процент, тем стабильнее рынок.',
  openOnWfm: 'Открыть на WFM',
  wfmItemHint: 'Открыть страницу этого предмета на Warframe Market',
  specialFilter: 'Особый фильтр',
  currentBaro: 'Ассортимент Баро',
  currentBaroHint: 'Показать торгуемые предметы из текущего ассортимента Баро Ки’Тиира',
  latestBaroHint: 'Баро Ки’Тиир уже ушёл. Показать торгуемые предметы из его последнего завершившегося ассортимента',
  currentBaroEmpty: 'Торгуемые предметы из последнего ассортимента Баро Ки’Тиира пока не сопоставлены',
  currentResurgence: 'Текущее Возрождение Прайм',
  currentResurgenceHint: 'Показать все торгуемые предметы и части текущего Возрождения Прайм, кроме семейств Бёрстона, Брэйтона, Клыков и Лекса Прайм',
  currentResurgenceEmpty: 'Торгуемые предметы текущего Возрождения Прайм пока не сопоставлены',
  tableColumns: 'Столбцы таблицы',
  chooseTableColumns: 'Выбрать столбцы таблицы',
  tableSettings: 'Отображение таблицы',
  chooseTableSettings: 'Выбрать диапазоны и столбцы',
  priceChangeColumns: 'Изменение цены',
  otherColumns: 'Аналитика',
  salesColumns: 'Промежутки продаж',
  potentialColumn: 'Потенциал',
  scoreColumn: 'Оценка',
  forecastColumn: 'Прогноз',
  sales: 'Продажи'
}

export const getExtraText = (locale: Locale): ExtraText => locale === 'ru' ? ru : en
