import type { Locale } from './i18n'

export type InfoPageKind = 'about' | 'faq' | 'privacy' | 'terms' | 'contact'

type InfoSection = { title?: string; paragraphs: readonly string[]; bullets?: readonly string[] }
type InfoDocument = { title: string; intro?: string; updated?: string; sections: readonly InfoSection[] }
type InfoLocaleCopy = {
  back: string
  navigationLabel: string
  nav: Record<InfoPageKind, string>
  pages: Record<InfoPageKind, InfoDocument>
}

export const INFO_PAGE_PATHS: Record<InfoPageKind, string> = {
  about: '/about', faq: '/faq', privacy: '/privacy', terms: '/terms', contact: '/contact',
}

const section = (title: string | undefined, ...paragraphs: string[]): InfoSection => ({ title, paragraphs })

export const infoCopy: Record<Locale, InfoLocaleCopy> = {
  ru: {
    back: 'На главную', navigationLabel: 'Информация о FrameAnalytics',
    nav: { about: 'О проекте', faq: 'FAQ', privacy: 'Политика конфиденциальности', terms: 'Условия пользования', contact: 'Связаться' },
    pages: {
      about: {
        title: 'О проекте', intro: 'FrameAnalytics — независимый аналитический сервис для игроков Warframe.',
        sections: [section(undefined,
          'Он помогает изучать изменения цен, сравнивать предметы, отслеживать рыночную активность и находить потенциально интересные варианты покупки или продажи.',
          'Доступные инструменты включают основную аналитическую таблицу, личный профиль, Умную покупку, советник по продаже и специализированные сканеры.',
          'Все показатели, прогнозы и расчёты носят информационный характер. Рыночная ситуация может измениться в любой момент, поэтому перед сделкой рекомендуется самостоятельно проверить цену и доступность предложения.',
          'FrameAnalytics не связан с Digital Extremes или Warframe Market и не представляет их интересы. Названия и материалы соответствующих проектов принадлежат их правообладателям.'
        )],
      },
      faq: {
        title: 'Частые вопросы', sections: [
          section('Откуда берутся цены?', 'FrameAnalytics использует доступные рыночные данные и накопленную статистику Warframe Market. Сервис не устанавливает цены и не управляет предложениями игроков.'),
          section('Почему цена может отличаться от текущего предложения?', 'Активный ордер может быть изменён или удалён между обновлениями. Перед сделкой всегда проверяйте актуальную цену непосредственно на странице предложения.'),
          section('Что означает потенциальная прибыль?', 'Это расчётная разница между текущей ценой и выбранным ориентиром. Она не гарантирует, что предмет удастся купить или продать по указанной цене.'),
          section('Что делают Умная покупка и советник по продаже?', 'Эти инструменты анализируют доступные предложения и формируют рекомендации. Они не совершают сделки, не отправляют сообщения игрокам и не изменяют ордера автоматически.'),
          section('Почему сканирование иногда занимает время?', 'Некоторые операции выполняются последовательно или могут ожидать своей очереди. Это необходимо для стабильной работы сервиса и используемых источников данных.'),
          section('Нужен ли пароль от Warframe Market?', 'Нет. FrameAnalytics не должен запрашивать пароль, одноразовый код или другие секретные данные от вашего игрового или рыночного аккаунта.'),
          section('Где сохраняются мои покупки?', 'После входа добавленные покупки могут сохраняться в профиле FrameAnalytics. Настройки внешнего вида и таблиц также могут храниться в текущем браузере.'),
          section('Как сообщить об ошибке?', 'Откройте страницу «Связаться» и укажите страницу, последовательность действий и текст ошибки. Не прикладывайте пароли, токены и другие секретные данные.'),
        ],
      },
      privacy: {
        title: 'Политика конфиденциальности', updated: 'Дата обновления: 1 сентября 2026 года.',
        intro: 'FrameAnalytics обрабатывает только информацию, необходимую для работы сайта, аккаунтов и пользовательских функций.',
        sections: [
          { title: 'Какие данные могут обрабатываться', paragraphs: ['При создании и использовании аккаунта могут сохраняться:'], bullets: ['адрес электронной почты;', 'данные, необходимые для поддержания активного входа;', 'настройки профиля и интерфейса;', 'добавленные пользователем покупки;', 'выданные аккаунту разрешения;', 'информация, которую пользователь самостоятельно добавляет в профиль.'] },
          section(undefined, 'Для защиты сервиса и поиска ошибок также могут временно обрабатываться технические сведения о запросах и работе сайта.', 'FrameAnalytics не запрашивает пароль от Warframe Market, одноразовые коды или другие секретные данные сторонних аккаунтов.'),
          { title: 'Для чего используются данные', paragraphs: ['Информация используется для:'], bullets: ['входа и защиты аккаунта;', 'сохранения профиля и пользовательских настроек;', 'работы персональных инструментов;', 'предотвращения злоупотреблений;', 'диагностики и исправления ошибок.'] },
          section('Данные в браузере', 'Браузер может сохранять выбранный язык, тему, настройки таблиц и другие параметры интерфейса. Их можно удалить через настройки браузера.'),
          section('Сторонние сервисы', 'Для размещения и работы сайта могут использоваться технические поставщики услуг. Они получают только тот объём данных, который необходим для выполнения соответствующей функции.', 'При переходе на внешний сайт применяются правила конфиденциальности этого сайта.'),
          section('Срок хранения', 'Данные аккаунта хранятся до удаления аккаунта или обработки подтверждённого запроса на удаление. Технические журналы хранятся только в течение периода, необходимого для обеспечения безопасности и диагностики.'),
          section('Управление данными', 'Пользователь может запросить доступ, исправление или удаление своих данных, отправив личное сообщение в Discord пользователю `azulor`.', 'Перед выполнением запроса может потребоваться подтверждение принадлежности аккаунта.'),
        ],
      },
      terms: {
        title: 'Условия пользования', updated: 'Дата обновления: 1 сентября 2026 года.', intro: 'Используя FrameAnalytics, вы соглашаетесь с настоящими условиями.',
        sections: [
          section('Назначение сервиса', 'FrameAnalytics предоставляет аналитические данные и вспомогательные инструменты для изучения рынка Warframe.', 'Цены, прогнозы, рекомендации и расчёты потенциальной прибыли являются ориентировочными и не гарантируют успешную сделку или получение прибыли.'),
          section('Ответственность пользователя', 'Пользователь самостоятельно принимает решение о покупке или продаже предмета и обязан проверить цену, количество, характеристики предмета и имя участника сделки.', 'FrameAnalytics не является стороной сделки, не хранит игровые предметы или платину и не подтверждает сделки от имени пользователя.'),
          section('Аккаунт', 'Пользователь отвечает за сохранность доступа к своему аккаунту. Запрещено использовать чужие учётные данные, обходить ограничения доступа или пытаться получить функции, на которые аккаунту не выдано разрешение.'),
          { title: 'Допустимое использование', paragraphs: ['Запрещено:'], bullets: ['создавать чрезмерную нагрузку на сайт;', 'пытаться нарушить или обойти защитные механизмы;', 'получать несанкционированный доступ к данным или функциям;', 'использовать сервис для обмана, мошенничества или нарушения правил сторонних площадок.'] },
          section('Сторонние ресурсы', 'FrameAnalytics может содержать ссылки на внешние сайты. Их доступность, содержание и правила находятся вне контроля FrameAnalytics.'),
          section('Изменения и доступность', 'Отдельные функции могут изменяться, временно отключаться или предоставляться ограниченному кругу пользователей.', 'Условия могут обновляться вместе с развитием проекта. Дата последнего изменения указывается в начале страницы.'),
          section('Связь', 'Вопросы по условиям использования можно направить личным сообщением в Discord пользователю `azulor`.'),
        ],
      },
      contact: {
        title: 'Связаться', intro: 'По вопросам работы FrameAnalytics отправьте личное сообщение в Discord пользователю `azulor`.',
        sections: [
          { title: 'Сообщить об ошибке', paragraphs: ['Чтобы можно было воспроизвести проблему, укажите:'], bullets: ['страницу, на которой возникла ошибка;', 'дату и примерное время;', 'последовательность действий;', 'полный текст сообщения об ошибке;', 'скриншот, если он помогает понять проблему.'] },
          section(undefined, 'Не отправляйте пароли, коды подтверждения, токены доступа и другие секретные данные.'),
          section('Предложить функцию', 'Опишите, какую задачу вы хотите решить и какой результат ожидаете получить. Готовый вариант интерфейса предлагать необязательно.'),
          section('Вопрос по аккаунту', 'Укажите адрес электронной почты аккаунта и кратко опишите проблему. Для удаления или восстановления данных может потребоваться подтверждение принадлежности аккаунта.'),
          section('Вопрос безопасности', 'Если вы обнаружили уязвимость, не публикуйте подробности в открытом доступе. Отправьте описание личным сообщением в Discord пользователю `azulor`.'),
        ],
      },
    },
  },
  en: {
    back: 'Home', navigationLabel: 'FrameAnalytics information',
    nav: { about: 'About', faq: 'FAQ', privacy: 'Privacy Policy', terms: 'Terms of Use', contact: 'Contact' },
    pages: {
      about: { title: 'About', intro: 'FrameAnalytics is an independent analytics service for Warframe players.', sections: [section(undefined, 'It helps users explore price changes, compare items, track market activity, and find potentially interesting buying or selling opportunities.', 'Available tools include the main analytics table, personal profile, Smart Buy, Sell Advisor, and specialized scanners.', 'All metrics, forecasts, and calculations are informational. Market conditions can change at any time, so verify an offer’s price and availability before trading.', 'FrameAnalytics is not affiliated with Digital Extremes or Warframe Market and does not represent them. Their names and materials belong to their respective owners.', 'The service is in testing. Its interface, calculations, and available features may change.')] },
      faq: { title: 'Frequently Asked Questions', sections: [section('Where do prices come from?', 'FrameAnalytics uses available market data and accumulated Warframe Market statistics. It does not set prices or manage player offers.'), section('Why can a price differ from a current offer?', 'An active order may be changed or removed between updates. Always verify the current price on the offer page before trading.'), section('What is potential profit?', 'It is the calculated difference between the current price and a selected reference. It does not guarantee a purchase or sale at that price.'), section('What do Smart Buy and Sell Advisor do?', 'They analyze available offers and prepare recommendations. They do not trade, message players, or change orders automatically.'), section('Why can scanning take time?', 'Some operations run sequentially or wait in a queue to keep the service and its data sources stable.'), section('Is my Warframe Market password required?', 'No. FrameAnalytics must never ask for passwords, one-time codes, or other secrets from your game or market account.'), section('Where are my purchases saved?', 'After sign-in, purchases may be saved in your FrameAnalytics profile. Appearance and table settings may also stay in this browser.'), section('How do I report a bug?', 'Open the Contact page and include the page, steps, and error text. Never attach passwords, tokens, or other secrets.')] },
      privacy: { title: 'Privacy Policy', updated: 'Last updated: September 1, 2026.', intro: 'FrameAnalytics processes only the information needed to operate the site, accounts, and user features.', sections: [section('Data that may be processed', 'Account data may include an email address, active sign-in data, profile and interface settings, saved purchases, granted permissions, and information you add to your profile. Technical request data may be processed temporarily for security and diagnostics. FrameAnalytics does not request Warframe Market passwords, one-time codes, or other third-party secrets.'), section('How data is used', 'Data is used to sign in and protect accounts, save profiles and settings, operate personal tools, prevent abuse, and diagnose errors.'), section('Browser data', 'Your browser may save language, theme, table settings, and other interface preferences. You can remove them in browser settings.'), section('Third-party services', 'Technical providers may be used to host and operate the site and receive only the data needed for that function. External sites apply their own privacy rules.'), section('Retention', 'Account data is kept until the account is deleted or a verified deletion request is processed. Technical logs are kept only as long as required for security and diagnostics.'), section('Your data', 'Request access, correction, or deletion by sending a private Discord message to `azulor`. Account ownership may need to be verified first.')] },
      terms: { title: 'Terms of Use', updated: 'Last updated: September 1, 2026.', intro: 'By using FrameAnalytics, you agree to these terms.', sections: [section('Purpose', 'FrameAnalytics provides analytics and supporting tools for studying the Warframe market. Prices, forecasts, recommendations, and potential-profit calculations are estimates and do not guarantee a successful trade or profit.'), section('User responsibility', 'You decide whether to buy or sell and must verify the price, quantity, item details, and trader name. FrameAnalytics is not a party to a trade and does not hold items or Platinum.'), section('Account', 'You are responsible for account access. Do not use someone else’s credentials, bypass access controls, or seek features your account has not been granted.'), section('Acceptable use', 'Do not create excessive load, bypass protections, access data or features without authorization, or use the service for deception, fraud, or violations of third-party rules.'), section('External resources', 'FrameAnalytics may link to external sites whose availability, content, and rules it does not control.'), section('Changes and availability', 'During testing, features may change, be temporarily disabled, or be limited to some users. These terms may evolve; the latest date appears at the top of this page.'), section('Contact', 'Questions about these terms can be sent by private Discord message to `azulor`.')] },
      contact: { title: 'Contact', intro: 'For questions about FrameAnalytics, send a private Discord message to `azulor`.', sections: [section('Report a bug', 'Include the affected page, approximate date and time, steps, complete error text, and a helpful screenshot. Do not send passwords, verification codes, access tokens, or other secrets.'), section('Suggest a feature', 'Describe the problem you want to solve and the result you expect. A finished interface design is not required.'), section('Account question', 'Include the account email address and a short description. Deleting or restoring data may require proof that you own the account.'), section('Security issue', 'Do not publish vulnerability details. Send them privately on Discord to `azulor`.')] },
    },
  },
  de: {
    back: 'Startseite', navigationLabel: 'Informationen zu FrameAnalytics',
    nav: { about: 'Über das Projekt', faq: 'FAQ', privacy: 'Datenschutz', terms: 'Nutzungsbedingungen', contact: 'Kontakt' },
    pages: {
      about: { title: 'Über das Projekt', intro: 'FrameAnalytics ist ein unabhängiger Analysedienst für Warframe-Spieler.', sections: [section(undefined, 'Der Dienst hilft, Preisänderungen zu untersuchen, Gegenstände zu vergleichen, Marktaktivitäten zu verfolgen und interessante Kauf- oder Verkaufsmöglichkeiten zu finden.', 'Zu den Werkzeugen gehören die zentrale Analysetabelle, das persönliche Profil, Smart Buy, Sell Advisor und spezialisierte Scanner.', 'Alle Kennzahlen, Prognosen und Berechnungen dienen nur zur Information. Prüfe Preis und Verfügbarkeit vor jedem Handel selbst.', 'FrameAnalytics ist weder mit Digital Extremes noch mit Warframe Market verbunden und vertritt sie nicht. Namen und Materialien gehören ihren jeweiligen Rechteinhabern.', 'Der Dienst befindet sich in der Testphase. Oberfläche, Berechnungen und Funktionsumfang können sich ändern.')] },
      faq: { title: 'Häufig gestellte Fragen', sections: [section('Woher stammen die Preise?', 'FrameAnalytics verwendet verfügbare Marktdaten und gesammelte Statistiken von Warframe Market. Der Dienst legt keine Preise fest und verwaltet keine Angebote.'), section('Warum kann ein Preis vom aktuellen Angebot abweichen?', 'Ein aktiver Auftrag kann zwischen Aktualisierungen geändert oder entfernt werden. Prüfe den aktuellen Preis vor dem Handel auf der Angebotsseite.'), section('Was bedeutet potenzieller Gewinn?', 'Das ist die berechnete Differenz zwischen aktuellem Preis und gewähltem Vergleichswert. Ein Kauf oder Verkauf zu diesem Preis wird nicht garantiert.'), section('Was machen Smart Buy und Sell Advisor?', 'Sie analysieren Angebote und erstellen Empfehlungen. Sie handeln nicht, senden keine Nachrichten und ändern keine Aufträge automatisch.'), section('Warum kann ein Scan dauern?', 'Einige Vorgänge laufen nacheinander oder warten in einer Warteschlange, damit Dienst und Datenquellen stabil bleiben.'), section('Wird mein Warframe-Market-Passwort benötigt?', 'Nein. FrameAnalytics darf niemals Passwörter, Einmalcodes oder andere Geheimnisse deines Spiel- oder Marktkontos verlangen.'), section('Wo werden meine Käufe gespeichert?', 'Nach der Anmeldung können Käufe im FrameAnalytics-Profil gespeichert werden. Darstellungs- und Tabelleneinstellungen können außerdem im Browser verbleiben.'), section('Wie melde ich einen Fehler?', 'Öffne die Kontaktseite und nenne Seite, Schritte und Fehlermeldung. Sende keine Passwörter, Tokens oder andere Geheimnisse.')] },
      privacy: { title: 'Datenschutzerklärung', updated: 'Stand: 1. September 2026.', intro: 'FrameAnalytics verarbeitet nur Informationen, die für Website, Konten und Benutzerfunktionen erforderlich sind.', sections: [section('Mögliche Daten', 'Verarbeitet werden können E-Mail-Adresse, Anmeldedaten, Profil- und Oberflächeneinstellungen, gespeicherte Käufe, Berechtigungen und eigene Profilangaben. Technische Anfragedaten können vorübergehend für Sicherheit und Diagnose verarbeitet werden. Geheimnisse externer Konten werden nicht abgefragt.'), section('Verwendung', 'Daten dienen Anmeldung und Kontoschutz, Profil und Einstellungen, persönlichen Werkzeugen, Missbrauchsschutz und Fehlerdiagnose.'), section('Browserdaten', 'Sprache, Design, Tabelleneinstellungen und weitere Optionen können im Browser gespeichert und dort gelöscht werden.'), section('Drittanbieter', 'Technische Dienstleister erhalten nur Daten, die für Hosting und Betrieb erforderlich sind. Für externe Websites gelten deren eigene Datenschutzregeln.'), section('Speicherdauer', 'Kontodaten bleiben bis zur Kontolöschung oder Bearbeitung eines bestätigten Löschantrags gespeichert. Technische Protokolle nur so lange, wie Sicherheit und Diagnose es erfordern.'), section('Datenrechte', 'Zugriff, Berichtigung oder Löschung per privater Discord-Nachricht an `azulor` anfordern. Ein Eigentumsnachweis kann nötig sein.')] },
      terms: { title: 'Nutzungsbedingungen', updated: 'Stand: 1. September 2026.', intro: 'Mit der Nutzung von FrameAnalytics stimmst du diesen Bedingungen zu.', sections: [section('Zweck', 'FrameAnalytics bietet Analysen und Hilfswerkzeuge für den Warframe-Markt. Preise, Prognosen, Empfehlungen und Gewinnberechnungen sind Richtwerte ohne Erfolgs- oder Gewinngarantie.'), section('Verantwortung', 'Du entscheidest selbst über Käufe und Verkäufe und prüfst Preis, Menge, Gegenstand und Handelspartner. FrameAnalytics ist keine Handelspartei und verwahrt weder Gegenstände noch Platinum.'), section('Konto', 'Du bist für den Kontozugang verantwortlich. Fremde Zugangsdaten, Umgehung von Zugriffsbeschränkungen und nicht erteilte Funktionen sind verboten.'), section('Zulässige Nutzung', 'Keine übermäßige Last, Umgehung von Schutzmaßnahmen, unbefugten Zugriffe, Täuschung, Betrug oder Verstöße gegen Regeln Dritter.'), section('Externe Ressourcen', 'Für Verfügbarkeit, Inhalte und Regeln verlinkter externer Websites ist FrameAnalytics nicht verantwortlich.'), section('Änderungen und Verfügbarkeit', 'Während der Testphase können Funktionen geändert, vorübergehend deaktiviert oder eingeschränkt werden. Diese Bedingungen können aktualisiert werden.'), section('Kontakt', 'Fragen per privater Discord-Nachricht an `azulor`.')] },
      contact: { title: 'Kontakt', intro: 'Fragen zu FrameAnalytics per privater Discord-Nachricht an `azulor` senden.', sections: [section('Fehler melden', 'Nenne betroffene Seite, ungefähres Datum und Uhrzeit, Schritte, vollständigen Fehlertext und bei Bedarf einen Screenshot. Sende keine Passwörter, Codes, Tokens oder andere Geheimnisse.'), section('Funktion vorschlagen', 'Beschreibe Aufgabe und gewünschtes Ergebnis. Ein fertiger Oberflächenentwurf ist nicht nötig.'), section('Kontofrage', 'Nenne die E-Mail-Adresse des Kontos und beschreibe das Problem kurz. Löschen oder Wiederherstellen kann einen Eigentumsnachweis erfordern.'), section('Sicherheitsproblem', 'Veröffentliche keine Schwachstellendetails. Sende sie privat über Discord an `azulor`.')] },
    },
  },
  fr: {
    back: 'Accueil', navigationLabel: 'Informations sur FrameAnalytics',
    nav: { about: 'À propos', faq: 'FAQ', privacy: 'Confidentialité', terms: 'Conditions d’utilisation', contact: 'Contact' },
    pages: {
      about: { title: 'À propos', intro: 'FrameAnalytics est un service d’analyse indépendant destiné aux joueurs de Warframe.', sections: [section(undefined, 'Il aide à étudier les variations de prix, comparer les objets, suivre l’activité du marché et repérer des possibilités intéressantes d’achat ou de vente.', 'Les outils comprennent la table d’analyse principale, le profil personnel, Smart Buy, Sell Advisor et des scanners spécialisés.', 'Tous les indicateurs, prévisions et calculs sont informatifs. Vérifiez vous-même le prix et la disponibilité avant toute transaction.', 'FrameAnalytics n’est affilié ni à Digital Extremes ni à Warframe Market et ne les représente pas. Leurs noms et contenus appartiennent à leurs ayants droit.', 'Le service est en phase de test. Son interface, ses calculs et ses fonctions peuvent évoluer.')] },
      faq: { title: 'Questions fréquentes', sections: [section('D’où viennent les prix ?', 'FrameAnalytics utilise les données de marché disponibles et les statistiques accumulées de Warframe Market. Il ne fixe pas les prix et ne gère pas les offres.'), section('Pourquoi un prix peut-il différer d’une offre actuelle ?', 'Un ordre actif peut être modifié ou supprimé entre deux mises à jour. Vérifiez toujours le prix actuel sur la page de l’offre.'), section('Que signifie le bénéfice potentiel ?', 'Il s’agit de la différence calculée entre le prix actuel et une référence choisie. Aucun achat ou vente à ce prix n’est garanti.'), section('Que font Smart Buy et Sell Advisor ?', 'Ils analysent les offres et préparent des recommandations. Ils ne négocient pas, n’envoient pas de messages et ne modifient pas les ordres automatiquement.'), section('Pourquoi un scan peut-il prendre du temps ?', 'Certaines opérations sont séquentielles ou attendent dans une file afin de préserver la stabilité du service et des sources.'), section('Mon mot de passe Warframe Market est-il nécessaire ?', 'Non. FrameAnalytics ne doit jamais demander de mot de passe, de code à usage unique ni d’autre secret lié à vos comptes.'), section('Où mes achats sont-ils enregistrés ?', 'Après connexion, ils peuvent être enregistrés dans votre profil FrameAnalytics. Les réglages d’affichage et de table peuvent aussi rester dans le navigateur.'), section('Comment signaler un bug ?', 'Ouvrez la page Contact et indiquez la page, les étapes et le message d’erreur. Ne joignez jamais de mot de passe, jeton ou autre secret.')] },
      privacy: { title: 'Politique de confidentialité', updated: 'Mise à jour : 1er septembre 2026.', intro: 'FrameAnalytics ne traite que les informations nécessaires au site, aux comptes et aux fonctions utilisateur.', sections: [section('Données susceptibles d’être traitées', 'Elles peuvent inclure adresse e-mail, données de connexion, réglages du profil et de l’interface, achats enregistrés, autorisations et informations ajoutées au profil. Des données techniques peuvent être traitées temporairement pour la sécurité et le diagnostic. Aucun secret de compte tiers n’est demandé.'), section('Utilisation', 'Les données servent à la connexion et à la protection du compte, aux profils et réglages, aux outils personnels, à la prévention des abus et au diagnostic des erreurs.'), section('Données du navigateur', 'La langue, le thème, les réglages des tables et d’autres préférences peuvent être enregistrés dans le navigateur et supprimés depuis ses paramètres.'), section('Services tiers', 'Les prestataires techniques ne reçoivent que les données nécessaires à l’hébergement et au fonctionnement. Les sites externes appliquent leurs propres règles.'), section('Conservation', 'Les données du compte sont conservées jusqu’à sa suppression ou au traitement d’une demande confirmée. Les journaux techniques ne le sont que le temps nécessaire à la sécurité et au diagnostic.'), section('Vos données', 'Demandez accès, rectification ou suppression par message Discord privé à `azulor`. Une vérification du compte peut être requise.')] },
      terms: { title: 'Conditions d’utilisation', updated: 'Mise à jour : 1er septembre 2026.', intro: 'En utilisant FrameAnalytics, vous acceptez ces conditions.', sections: [section('Objet', 'FrameAnalytics fournit des analyses et des outils d’aide pour le marché Warframe. Prix, prévisions, recommandations et bénéfices potentiels sont indicatifs et ne garantissent ni transaction ni profit.'), section('Responsabilité', 'Vous décidez de chaque achat ou vente et devez vérifier prix, quantité, objet et nom du partenaire. FrameAnalytics n’est pas partie à la transaction et ne détient ni objets ni Platinum.'), section('Compte', 'Vous êtes responsable de son accès. Il est interdit d’utiliser les identifiants d’autrui, de contourner les contrôles ou d’obtenir des fonctions non autorisées.'), section('Usage acceptable', 'Pas de charge excessive, contournement des protections, accès non autorisé, tromperie, fraude ou violation des règles de tiers.'), section('Ressources externes', 'FrameAnalytics ne contrôle pas la disponibilité, le contenu ni les règles des sites externes liés.'), section('Modifications et disponibilité', 'En phase de test, des fonctions peuvent changer, être suspendues ou limitées. Ces conditions peuvent être mises à jour.'), section('Contact', 'Questions par message Discord privé à `azulor`.')] },
      contact: { title: 'Contact', intro: 'Pour toute question sur FrameAnalytics, envoyez un message Discord privé à `azulor`.', sections: [section('Signaler un bug', 'Indiquez la page, la date et l’heure approximatives, les étapes, le message complet et éventuellement une capture. N’envoyez pas de mots de passe, codes, jetons ou autres secrets.'), section('Proposer une fonction', 'Décrivez le problème à résoudre et le résultat attendu. Une maquette complète n’est pas nécessaire.'), section('Question de compte', 'Indiquez l’adresse e-mail du compte et décrivez brièvement le problème. La suppression ou restauration peut exiger une preuve de propriété.'), section('Sécurité', 'Ne publiez pas les détails d’une vulnérabilité. Envoyez-les en privé sur Discord à `azulor`.')] },
    },
  },
  es: {
    back: 'Inicio', navigationLabel: 'Información de FrameAnalytics',
    nav: { about: 'Acerca del proyecto', faq: 'Preguntas frecuentes', privacy: 'Privacidad', terms: 'Condiciones de uso', contact: 'Contacto' },
    pages: {
      about: { title: 'Acerca del proyecto', intro: 'FrameAnalytics es un servicio de análisis independiente para jugadores de Warframe.', sections: [section(undefined, 'Ayuda a estudiar cambios de precio, comparar objetos, seguir la actividad del mercado y encontrar posibles oportunidades de compra o venta.', 'Sus herramientas incluyen la tabla principal, el perfil personal, Smart Buy, Sell Advisor y escáneres especializados.', 'Todos los indicadores, pronósticos y cálculos son informativos. Comprueba el precio y la disponibilidad antes de comerciar.', 'FrameAnalytics no está afiliado con Digital Extremes ni Warframe Market y no los representa. Sus nombres y materiales pertenecen a sus titulares.', 'El servicio está en pruebas. La interfaz, los cálculos y las funciones disponibles pueden cambiar.')] },
      faq: { title: 'Preguntas frecuentes', sections: [section('¿De dónde salen los precios?', 'FrameAnalytics usa datos de mercado disponibles y estadísticas acumuladas de Warframe Market. No fija precios ni administra ofertas.'), section('¿Por qué un precio puede diferir de una oferta actual?', 'Una orden activa puede cambiar o eliminarse entre actualizaciones. Comprueba siempre el precio en la página de la oferta.'), section('¿Qué significa beneficio potencial?', 'Es la diferencia calculada entre el precio actual y una referencia elegida. No garantiza comprar o vender a ese precio.'), section('¿Qué hacen Smart Buy y Sell Advisor?', 'Analizan ofertas y preparan recomendaciones. No comercian, no envían mensajes ni cambian órdenes automáticamente.'), section('¿Por qué puede tardar un escaneo?', 'Algunas operaciones son secuenciales o esperan en una cola para mantener estables el servicio y las fuentes.'), section('¿Necesito mi contraseña de Warframe Market?', 'No. FrameAnalytics nunca debe pedir contraseñas, códigos de un solo uso ni otros secretos de tus cuentas.'), section('¿Dónde se guardan mis compras?', 'Tras iniciar sesión, pueden guardarse en tu perfil de FrameAnalytics. Los ajustes visuales y de tablas también pueden quedar en el navegador.'), section('¿Cómo informo de un error?', 'Abre Contacto e indica la página, los pasos y el texto del error. No adjuntes contraseñas, tokens ni otros secretos.')] },
      privacy: { title: 'Política de privacidad', updated: 'Actualizada: 1 de septiembre de 2026.', intro: 'FrameAnalytics procesa solo la información necesaria para el sitio, las cuentas y las funciones de usuario.', sections: [section('Datos que pueden procesarse', 'Pueden incluir correo electrónico, datos de inicio de sesión, ajustes de perfil e interfaz, compras guardadas, permisos e información añadida al perfil. Los datos técnicos pueden procesarse temporalmente por seguridad y diagnóstico. No se piden secretos de cuentas externas.'), section('Uso de los datos', 'Se usan para iniciar sesión y proteger cuentas, guardar perfiles y ajustes, operar herramientas personales, evitar abusos y diagnosticar errores.'), section('Datos del navegador', 'El idioma, tema, ajustes de tablas y otras preferencias pueden guardarse en el navegador y eliminarse desde su configuración.'), section('Servicios de terceros', 'Los proveedores técnicos reciben solo los datos necesarios para alojar y operar el sitio. Los sitios externos aplican sus propias políticas.'), section('Conservación', 'Los datos de cuenta se conservan hasta borrar la cuenta o procesar una solicitud de eliminación verificada. Los registros técnicos solo durante el tiempo necesario para seguridad y diagnóstico.'), section('Tus datos', 'Solicita acceso, corrección o eliminación por mensaje privado de Discord a `azulor`. Puede ser necesario verificar la cuenta.')] },
      terms: { title: 'Condiciones de uso', updated: 'Actualizadas: 1 de septiembre de 2026.', intro: 'Al usar FrameAnalytics aceptas estas condiciones.', sections: [section('Finalidad', 'FrameAnalytics ofrece análisis y herramientas de apoyo para el mercado de Warframe. Precios, pronósticos, recomendaciones y beneficios potenciales son orientativos y no garantizan operación ni ganancia.'), section('Responsabilidad', 'Tú decides comprar o vender y debes verificar precio, cantidad, objeto y nombre del comerciante. FrameAnalytics no participa en la operación ni guarda objetos o Platinum.'), section('Cuenta', 'Eres responsable del acceso. No uses credenciales ajenas, eludas controles ni intentes obtener funciones no concedidas.'), section('Uso aceptable', 'No provoques carga excesiva, eludas protecciones, accedas sin autorización ni uses el servicio para engaño, fraude o infringir reglas externas.'), section('Recursos externos', 'FrameAnalytics no controla disponibilidad, contenido ni reglas de sitios externos enlazados.'), section('Cambios y disponibilidad', 'Durante las pruebas, las funciones pueden cambiar, desactivarse o limitarse. Estas condiciones también pueden actualizarse.'), section('Contacto', 'Envía preguntas por mensaje privado de Discord a `azulor`.')] },
      contact: { title: 'Contacto', intro: 'Para consultas sobre FrameAnalytics, envía un mensaje privado de Discord a `azulor`.', sections: [section('Informar de un error', 'Incluye página, fecha y hora aproximadas, pasos, mensaje completo y una captura útil. No envíes contraseñas, códigos, tokens ni otros secretos.'), section('Proponer una función', 'Describe el problema y el resultado esperado. No hace falta un diseño terminado.'), section('Problema de cuenta', 'Indica el correo de la cuenta y describe brevemente el problema. Borrar o restaurar datos puede requerir verificar la propiedad.'), section('Seguridad', 'No publiques detalles de vulnerabilidades. Envíalos en privado por Discord a `azulor`.')] },
    },
  },
  pt: {
    back: 'Início', navigationLabel: 'Informações do FrameAnalytics',
    nav: { about: 'Sobre o projeto', faq: 'Perguntas frequentes', privacy: 'Privacidade', terms: 'Termos de uso', contact: 'Contato' },
    pages: {
      about: { title: 'Sobre o projeto', intro: 'FrameAnalytics é um serviço de análise independente para jogadores de Warframe.', sections: [section(undefined, 'Ele ajuda a estudar mudanças de preço, comparar itens, acompanhar a atividade do mercado e encontrar possíveis oportunidades de compra ou venda.', 'As ferramentas incluem a tabela principal, o perfil pessoal, Smart Buy, Sell Advisor e scanners especializados.', 'Todos os indicadores, previsões e cálculos são informativos. Verifique preço e disponibilidade antes de negociar.', 'FrameAnalytics não é afiliado à Digital Extremes nem ao Warframe Market e não os representa. Seus nomes e materiais pertencem aos respectivos titulares.', 'O serviço está em testes. Interface, cálculos e recursos disponíveis podem mudar.')] },
      faq: { title: 'Perguntas frequentes', sections: [section('De onde vêm os preços?', 'FrameAnalytics usa dados de mercado disponíveis e estatísticas acumuladas do Warframe Market. Não define preços nem administra ofertas.'), section('Por que o preço pode diferir de uma oferta atual?', 'Uma ordem ativa pode ser alterada ou removida entre atualizações. Confira o preço na página da oferta antes de negociar.'), section('O que significa lucro potencial?', 'É a diferença calculada entre o preço atual e uma referência escolhida. Não garante compra ou venda nesse preço.'), section('O que fazem Smart Buy e Sell Advisor?', 'Eles analisam ofertas e preparam recomendações. Não negociam, enviam mensagens ou alteram ordens automaticamente.'), section('Por que uma varredura pode demorar?', 'Algumas operações são sequenciais ou aguardam em fila para manter o serviço e as fontes estáveis.'), section('Preciso da senha do Warframe Market?', 'Não. FrameAnalytics nunca deve pedir senhas, códigos únicos ou outros segredos de suas contas.'), section('Onde minhas compras são salvas?', 'Após entrar, elas podem ser salvas no perfil FrameAnalytics. Preferências visuais e de tabelas também podem ficar no navegador.'), section('Como relatar um erro?', 'Abra Contato e informe página, passos e texto do erro. Não anexe senhas, tokens ou outros segredos.')] },
      privacy: { title: 'Política de privacidade', updated: 'Atualizada em 1 de setembro de 2026.', intro: 'FrameAnalytics processa apenas informações necessárias ao site, às contas e aos recursos do usuário.', sections: [section('Dados que podem ser processados', 'Podem incluir e-mail, dados de login, configurações de perfil e interface, compras salvas, permissões e informações adicionadas ao perfil. Dados técnicos podem ser processados temporariamente para segurança e diagnóstico. Segredos de contas externas não são solicitados.'), section('Uso dos dados', 'Os dados servem para login e proteção, perfis e configurações, ferramentas pessoais, prevenção de abuso e diagnóstico de erros.'), section('Dados do navegador', 'Idioma, tema, tabelas e outras preferências podem ser salvos no navegador e removidos nas configurações.'), section('Terceiros', 'Provedores técnicos recebem apenas o necessário para hospedar e operar o site. Sites externos aplicam suas próprias políticas.'), section('Retenção', 'Dados da conta ficam até a exclusão ou o processamento de um pedido confirmado. Logs técnicos ficam somente pelo período necessário para segurança e diagnóstico.'), section('Seus dados', 'Peça acesso, correção ou exclusão por mensagem privada no Discord para `azulor`. Pode ser necessário confirmar a conta.')] },
      terms: { title: 'Termos de uso', updated: 'Atualizados em 1 de setembro de 2026.', intro: 'Ao usar FrameAnalytics, você aceita estes termos.', sections: [section('Finalidade', 'FrameAnalytics oferece análises e ferramentas de apoio para o mercado de Warframe. Preços, previsões, recomendações e lucros potenciais são estimativas sem garantia de negociação ou lucro.'), section('Responsabilidade', 'Você decide comprar ou vender e deve conferir preço, quantidade, item e nome do comerciante. FrameAnalytics não participa da negociação nem guarda itens ou Platinum.'), section('Conta', 'Você é responsável pelo acesso. Não use credenciais alheias, contorne controles ou busque recursos não concedidos.'), section('Uso aceitável', 'Não cause carga excessiva, contorne proteções, acesse sem autorização nem use o serviço para engano, fraude ou violação de regras externas.'), section('Recursos externos', 'FrameAnalytics não controla disponibilidade, conteúdo ou regras de sites externos vinculados.'), section('Mudanças e disponibilidade', 'Durante os testes, recursos podem mudar, ser desativados ou limitados. Estes termos também podem ser atualizados.'), section('Contato', 'Envie dúvidas por mensagem privada no Discord para `azulor`.')] },
      contact: { title: 'Contato', intro: 'Para dúvidas sobre FrameAnalytics, envie uma mensagem privada no Discord para `azulor`.', sections: [section('Relatar um erro', 'Inclua página, data e hora aproximadas, passos, mensagem completa e uma captura útil. Não envie senhas, códigos, tokens ou outros segredos.'), section('Sugerir um recurso', 'Descreva o problema e o resultado esperado. Um design pronto não é necessário.'), section('Questão de conta', 'Informe o e-mail da conta e descreva brevemente o problema. Excluir ou restaurar dados pode exigir comprovação de propriedade.'), section('Segurança', 'Não publique detalhes de vulnerabilidades. Envie-os em privado pelo Discord para `azulor`.')] },
    },
  },
  pl: {
    back: 'Strona główna', navigationLabel: 'Informacje o FrameAnalytics',
    nav: { about: 'O projekcie', faq: 'FAQ', privacy: 'Prywatność', terms: 'Warunki korzystania', contact: 'Kontakt' },
    pages: {
      about: { title: 'O projekcie', intro: 'FrameAnalytics to niezależny serwis analityczny dla graczy Warframe.', sections: [section(undefined, 'Pomaga analizować zmiany cen, porównywać przedmioty, śledzić aktywność rynku i znajdować potencjalnie interesujące okazje kupna lub sprzedaży.', 'Narzędzia obejmują główną tabelę, profil, Smart Buy, Sell Advisor i wyspecjalizowane skanery.', 'Wszystkie wskaźniki, prognozy i obliczenia mają charakter informacyjny. Przed transakcją sprawdź cenę i dostępność oferty.', 'FrameAnalytics nie jest powiązany z Digital Extremes ani Warframe Market i ich nie reprezentuje. Nazwy i materiały należą do odpowiednich właścicieli.', 'Serwis jest w fazie testów. Interfejs, obliczenia i funkcje mogą się zmieniać.')] },
      faq: { title: 'Częste pytania', sections: [section('Skąd pochodzą ceny?', 'FrameAnalytics korzysta z dostępnych danych rynkowych i statystyk Warframe Market. Nie ustala cen ani nie zarządza ofertami.'), section('Dlaczego cena może różnić się od aktualnej oferty?', 'Aktywne zlecenie może zostać zmienione lub usunięte między aktualizacjami. Przed transakcją sprawdź cenę na stronie oferty.'), section('Co oznacza potencjalny zysk?', 'To obliczona różnica między bieżącą ceną a wybranym punktem odniesienia. Nie gwarantuje zakupu ani sprzedaży po tej cenie.'), section('Co robią Smart Buy i Sell Advisor?', 'Analizują oferty i przygotowują rekomendacje. Nie handlują, nie wysyłają wiadomości ani automatycznie nie zmieniają zleceń.'), section('Dlaczego skanowanie może potrwać?', 'Niektóre operacje wykonują się kolejno lub czekają w kolejce, aby zachować stabilność serwisu i źródeł.'), section('Czy potrzebne jest hasło Warframe Market?', 'Nie. FrameAnalytics nigdy nie powinien prosić o hasła, kody jednorazowe ani inne sekrety kont.'), section('Gdzie zapisywane są zakupy?', 'Po zalogowaniu mogą być zapisane w profilu FrameAnalytics. Ustawienia wyglądu i tabel mogą też pozostać w przeglądarce.'), section('Jak zgłosić błąd?', 'Otwórz stronę Kontakt i podaj stronę, kroki oraz tekst błędu. Nie dołączaj haseł, tokenów ani innych sekretów.')] },
      privacy: { title: 'Polityka prywatności', updated: 'Aktualizacja: 1 września 2026 r.', intro: 'FrameAnalytics przetwarza tylko informacje potrzebne do działania strony, kont i funkcji użytkownika.', sections: [section('Przetwarzane dane', 'Mogą obejmować e-mail, dane logowania, ustawienia profilu i interfejsu, zapisane zakupy, uprawnienia i informacje w profilu. Dane techniczne mogą być tymczasowo przetwarzane dla bezpieczeństwa i diagnostyki. Sekrety kont zewnętrznych nie są wymagane.'), section('Wykorzystanie', 'Dane służą do logowania i ochrony konta, profili i ustawień, narzędzi osobistych, zapobiegania nadużyciom i diagnozowania błędów.'), section('Dane przeglądarki', 'Język, motyw, ustawienia tabel i inne preferencje mogą być zapisane w przeglądarce i usunięte w jej ustawieniach.'), section('Usługi zewnętrzne', 'Dostawcy techniczni otrzymują tylko dane niezbędne do hostingu i działania. Zewnętrzne strony stosują własne zasady.'), section('Przechowywanie', 'Dane konta są przechowywane do usunięcia konta lub realizacji potwierdzonego wniosku. Logi techniczne tylko tak długo, jak wymaga bezpieczeństwo i diagnostyka.'), section('Twoje dane', 'O dostęp, korektę lub usunięcie poproś prywatną wiadomością Discord do `azulor`. Może być wymagana weryfikacja konta.')] },
      terms: { title: 'Warunki korzystania', updated: 'Aktualizacja: 1 września 2026 r.', intro: 'Korzystając z FrameAnalytics, akceptujesz te warunki.', sections: [section('Przeznaczenie', 'FrameAnalytics oferuje analizy i narzędzia pomocnicze dla rynku Warframe. Ceny, prognozy, rekomendacje i potencjalny zysk są szacunkowe i nie gwarantują transakcji ani zysku.'), section('Odpowiedzialność', 'Samodzielnie decydujesz o kupnie lub sprzedaży i sprawdzasz cenę, ilość, przedmiot oraz nazwę gracza. FrameAnalytics nie jest stroną transakcji i nie przechowuje przedmiotów ani Platinum.'), section('Konto', 'Odpowiadasz za dostęp. Nie używaj cudzych danych, nie omijaj ograniczeń i nie próbuj uzyskać nieprzyznanych funkcji.'), section('Dozwolone użycie', 'Nie powoduj nadmiernego obciążenia, nie omijaj zabezpieczeń, nie uzyskuj nieautoryzowanego dostępu i nie używaj serwisu do oszustw ani łamania zasad stron trzecich.'), section('Zasoby zewnętrzne', 'FrameAnalytics nie kontroluje dostępności, treści ani zasad zewnętrznych stron.'), section('Zmiany i dostępność', 'Podczas testów funkcje mogą się zmieniać, być wyłączane lub ograniczane. Warunki również mogą być aktualizowane.'), section('Kontakt', 'Pytania wyślij prywatnie na Discordzie do `azulor`.')] },
      contact: { title: 'Kontakt', intro: 'W sprawach FrameAnalytics wyślij prywatną wiadomość na Discordzie do `azulor`.', sections: [section('Zgłoszenie błędu', 'Podaj stronę, przybliżoną datę i godzinę, kroki, pełny komunikat oraz pomocny zrzut. Nie wysyłaj haseł, kodów, tokenów ani sekretów.'), section('Propozycja funkcji', 'Opisz problem i oczekiwany wynik. Gotowy projekt interfejsu nie jest potrzebny.'), section('Problem z kontem', 'Podaj e-mail konta i krótko opisz problem. Usunięcie lub odtworzenie danych może wymagać potwierdzenia własności.'), section('Bezpieczeństwo', 'Nie publikuj szczegółów luk. Wyślij je prywatnie na Discordzie do `azulor`.')] },
    },
  },
  uk: {
    back: 'На головну', navigationLabel: 'Інформація про FrameAnalytics',
    nav: { about: 'Про проєкт', faq: 'Поширені питання', privacy: 'Конфіденційність', terms: 'Умови користування', contact: 'Зв’язатися' },
    pages: {
      about: { title: 'Про проєкт', intro: 'FrameAnalytics — незалежний аналітичний сервіс для гравців Warframe.', sections: [section(undefined, 'Він допомагає досліджувати зміни цін, порівнювати предмети, стежити за активністю ринку та знаходити потенційно цікаві варіанти купівлі чи продажу.', 'Інструменти включають основну таблицю, особистий профіль, Smart Buy, Sell Advisor і спеціалізовані сканери.', 'Усі показники, прогнози й розрахунки мають інформаційний характер. Перед угодою самостійно перевіряйте ціну та доступність.', 'FrameAnalytics не пов’язаний із Digital Extremes або Warframe Market і не представляє їх. Назви й матеріали належать відповідним правовласникам.', 'Сервіс тестується. Інтерфейс, розрахунки та склад функцій можуть змінюватися.')] },
      faq: { title: 'Поширені питання', sections: [section('Звідки беруться ціни?', 'FrameAnalytics використовує доступні ринкові дані та накопичену статистику Warframe Market. Сервіс не встановлює ціни й не керує пропозиціями.'), section('Чому ціна може відрізнятися від поточної пропозиції?', 'Активне замовлення може бути змінене або видалене між оновленнями. Перед угодою перевіряйте актуальну ціну на сторінці пропозиції.'), section('Що означає потенційний прибуток?', 'Це розрахована різниця між поточною ціною та обраним орієнтиром. Вона не гарантує купівлю чи продаж за цією ціною.'), section('Що роблять Smart Buy і Sell Advisor?', 'Вони аналізують пропозиції та готують рекомендації. Вони не укладають угод, не надсилають повідомлень і не змінюють замовлення автоматично.'), section('Чому сканування може тривати?', 'Деякі операції виконуються послідовно або очікують у черзі для стабільності сервісу й джерел.'), section('Чи потрібен пароль Warframe Market?', 'Ні. FrameAnalytics не повинен запитувати паролі, одноразові коди чи інші секрети ваших облікових записів.'), section('Де зберігаються покупки?', 'Після входу вони можуть зберігатися у профілі FrameAnalytics. Налаштування вигляду й таблиць також можуть лишатися у браузері.'), section('Як повідомити про помилку?', 'Відкрийте сторінку «Зв’язатися» та вкажіть сторінку, дії й текст помилки. Не додавайте паролі, токени чи інші секрети.')] },
      privacy: { title: 'Політика конфіденційності', updated: 'Оновлено: 1 вересня 2026 року.', intro: 'FrameAnalytics обробляє лише інформацію, потрібну для роботи сайту, облікових записів і функцій користувача.', sections: [section('Дані, що можуть оброблятися', 'Це можуть бути email, дані входу, налаштування профілю та інтерфейсу, збережені покупки, дозволи й дані у профілі. Технічні відомості можуть тимчасово оброблятися для безпеки й діагностики. Секрети сторонніх акаунтів не запитуються.'), section('Використання', 'Дані потрібні для входу й захисту, профілів і налаштувань, персональних інструментів, запобігання зловживанням та діагностики.'), section('Дані браузера', 'Мова, тема, таблиці й інші параметри можуть зберігатися у браузері та видалятися в його налаштуваннях.'), section('Сторонні сервіси', 'Технічні постачальники отримують лише дані, необхідні для розміщення й роботи. Зовнішні сайти мають власні правила.'), section('Зберігання', 'Дані акаунта зберігаються до його видалення або виконання підтвердженого запиту. Технічні журнали — лише стільки, скільки потрібно для безпеки й діагностики.'), section('Ваші дані', 'Запит на доступ, виправлення чи видалення надішліть приватним повідомленням Discord користувачу `azulor`. Може знадобитися підтвердження акаунта.')] },
      terms: { title: 'Умови користування', updated: 'Оновлено: 1 вересня 2026 року.', intro: 'Використовуючи FrameAnalytics, ви погоджуєтеся з цими умовами.', sections: [section('Призначення', 'FrameAnalytics надає аналітику й допоміжні інструменти для ринку Warframe. Ціни, прогнози, рекомендації й потенційний прибуток є орієнтовними та не гарантують угоду чи прибуток.'), section('Відповідальність', 'Ви самі вирішуєте купувати чи продавати й перевіряєте ціну, кількість, предмет та ім’я учасника. FrameAnalytics не є стороною угоди й не зберігає предмети чи Platinum.'), section('Акаунт', 'Ви відповідаєте за доступ. Не використовуйте чужі дані, не обходьте обмеження й не намагайтеся отримати недозволені функції.'), section('Допустиме використання', 'Не створюйте надмірне навантаження, не обходьте захист, не отримуйте несанкціонований доступ і не використовуйте сервіс для обману, шахрайства чи порушення сторонніх правил.'), section('Зовнішні ресурси', 'FrameAnalytics не контролює доступність, вміст і правила зовнішніх сайтів.'), section('Зміни й доступність', 'Під час тестування функції можуть змінюватися, вимикатися чи обмежуватися. Умови також можуть оновлюватися.'), section('Зв’язок', 'Питання надсилайте приватним повідомленням Discord користувачу `azulor`.')] },
      contact: { title: 'Зв’язатися', intro: 'Щодо FrameAnalytics надішліть приватне повідомлення Discord користувачу `azulor`.', sections: [section('Повідомити про помилку', 'Укажіть сторінку, приблизні дату й час, послідовність дій, повний текст і корисний знімок. Не надсилайте паролі, коди, токени чи інші секрети.'), section('Запропонувати функцію', 'Опишіть задачу й очікуваний результат. Готовий дизайн інтерфейсу не потрібен.'), section('Питання щодо акаунта', 'Укажіть email акаунта й коротко опишіть проблему. Видалення або відновлення може вимагати підтвердження власності.'), section('Безпека', 'Не публікуйте подробиці вразливостей. Надішліть їх приватно в Discord користувачу `azulor`.')] },
    },
  },
  tr: {
    back: 'Ana sayfa', navigationLabel: 'FrameAnalytics bilgileri',
    nav: { about: 'Proje hakkında', faq: 'SSS', privacy: 'Gizlilik', terms: 'Kullanım koşulları', contact: 'İletişim' },
    pages: {
      about: { title: 'Proje hakkında', intro: 'FrameAnalytics, Warframe oyuncuları için bağımsız bir analiz hizmetidir.', sections: [section(undefined, 'Fiyat değişimlerini incelemeye, eşyaları karşılaştırmaya, piyasa etkinliğini izlemeye ve olası alım veya satım fırsatlarını bulmaya yardımcı olur.', 'Araçlar ana analiz tablosu, kişisel profil, Smart Buy, Sell Advisor ve özel tarayıcıları içerir.', 'Tüm göstergeler, tahminler ve hesaplamalar bilgi amaçlıdır. İşlemden önce fiyatı ve teklifin geçerliliğini kendiniz kontrol edin.', 'FrameAnalytics, Digital Extremes veya Warframe Market ile bağlantılı değildir ve onları temsil etmez. Adlar ve materyaller ilgili sahiplerine aittir.', 'Hizmet test aşamasındadır. Arayüz, hesaplamalar ve özellikler değişebilir.')] },
      faq: { title: 'Sık sorulan sorular', sections: [section('Fiyatlar nereden geliyor?', 'FrameAnalytics mevcut piyasa verilerini ve Warframe Market istatistiklerini kullanır. Fiyat belirlemez veya oyuncu tekliflerini yönetmez.'), section('Fiyat neden güncel tekliften farklı olabilir?', 'Etkin bir emir güncellemeler arasında değiştirilebilir veya silinebilir. İşlemden önce teklif sayfasındaki fiyatı kontrol edin.'), section('Potansiyel kâr nedir?', 'Güncel fiyat ile seçilen referans arasındaki hesaplanmış farktır. Bu fiyattan alım veya satım garantisi değildir.'), section('Smart Buy ve Sell Advisor ne yapar?', 'Teklifleri analiz eder ve öneri hazırlar. İşlem yapmaz, mesaj göndermez veya emirleri otomatik değiştirmez.'), section('Tarama neden zaman alabilir?', 'Bazı işlemler hizmeti ve kaynakları kararlı tutmak için sırayla çalışır veya kuyrukta bekler.'), section('Warframe Market parolam gerekli mi?', 'Hayır. FrameAnalytics parola, tek kullanımlık kod veya başka hesap sırlarını asla istememelidir.'), section('Alımlarım nerede saklanır?', 'Girişten sonra FrameAnalytics profilinde saklanabilir. Görünüm ve tablo ayarları tarayıcıda da kalabilir.'), section('Hata nasıl bildirilir?', 'İletişim sayfasını açıp sayfayı, adımları ve hata metnini yazın. Parola, token veya başka sır eklemeyin.')] },
      privacy: { title: 'Gizlilik politikası', updated: 'Güncelleme: 1 Eylül 2026.', intro: 'FrameAnalytics yalnızca site, hesaplar ve kullanıcı özellikleri için gereken bilgileri işler.', sections: [section('İşlenebilen veriler', 'E-posta, oturum verileri, profil ve arayüz ayarları, kaydedilmiş alımlar, izinler ve profile eklenen bilgiler işlenebilir. Teknik veriler güvenlik ve tanılama için geçici olarak işlenebilir. Harici hesap sırları istenmez.'), section('Kullanım', 'Veriler giriş ve hesap güvenliği, profil ve ayarlar, kişisel araçlar, kötüye kullanımı önleme ve hata tanılama için kullanılır.'), section('Tarayıcı verileri', 'Dil, tema, tablo ayarları ve diğer tercihler tarayıcıda saklanabilir ve ayarlardan silinebilir.'), section('Üçüncü taraflar', 'Teknik sağlayıcılar yalnızca barındırma ve işletim için gerekli verileri alır. Harici siteler kendi kurallarını uygular.'), section('Saklama', 'Hesap verileri hesap silinene veya doğrulanmış silme isteği işlenene kadar tutulur. Teknik günlükler yalnızca güvenlik ve tanılama için gereken süre tutulur.'), section('Verileriniz', 'Erişim, düzeltme veya silme için Discord’da `azulor` kullanıcısına özel mesaj gönderin. Hesap doğrulaması gerekebilir.')] },
      terms: { title: 'Kullanım koşulları', updated: 'Güncelleme: 1 Eylül 2026.', intro: 'FrameAnalytics’i kullanarak bu koşulları kabul edersiniz.', sections: [section('Amaç', 'FrameAnalytics Warframe piyasası için analiz ve yardımcı araçlar sunar. Fiyatlar, tahminler, öneriler ve potansiyel kârlar tahminidir; işlem veya kâr garantisi değildir.'), section('Sorumluluk', 'Alım veya satıma siz karar verir; fiyatı, miktarı, eşyayı ve oyuncu adını kontrol edersiniz. FrameAnalytics işlemin tarafı değildir ve eşya veya Platinum tutmaz.'), section('Hesap', 'Erişimden siz sorumlusunuz. Başkasının bilgilerini kullanmayın, kontrolleri aşmayın veya verilmemiş özellikleri almaya çalışmayın.'), section('Kabul edilebilir kullanım', 'Aşırı yük oluşturmayın, korumaları aşmayın, yetkisiz erişim sağlamayın ve hizmeti aldatma, dolandırıcılık veya harici kural ihlali için kullanmayın.'), section('Harici kaynaklar', 'FrameAnalytics bağlantılı harici sitelerin erişilebilirliğini, içeriğini veya kurallarını kontrol etmez.'), section('Değişiklikler ve erişim', 'Test sırasında özellikler değişebilir, kapatılabilir veya sınırlandırılabilir. Koşullar da güncellenebilir.'), section('İletişim', 'Soruları Discord’da `azulor` kullanıcısına özel mesajla gönderin.')] },
      contact: { title: 'İletişim', intro: 'FrameAnalytics ile ilgili sorular için Discord’da `azulor` kullanıcısına özel mesaj gönderin.', sections: [section('Hata bildir', 'Sayfayı, yaklaşık tarih ve saati, adımları, tam hata metnini ve yararlı bir ekran görüntüsünü ekleyin. Parola, kod, token veya başka sır göndermeyin.'), section('Özellik öner', 'Çözmek istediğiniz sorunu ve beklenen sonucu anlatın. Hazır bir arayüz tasarımı gerekmez.'), section('Hesap sorusu', 'Hesap e-postasını ve sorunu kısaca yazın. Silme veya geri yükleme sahiplik kanıtı gerektirebilir.'), section('Güvenlik', 'Açık ayrıntılarını yayımlamayın. Discord üzerinden `azulor` kullanıcısına özel gönderin.')] },
    },
  },
  it: {
    back: 'Home', navigationLabel: 'Informazioni su FrameAnalytics',
    nav: { about: 'Informazioni', faq: 'FAQ', privacy: 'Privacy', terms: 'Condizioni d’uso', contact: 'Contatti' },
    pages: {
      about: { title: 'Informazioni', intro: 'FrameAnalytics è un servizio di analisi indipendente per i giocatori di Warframe.', sections: [section(undefined, 'Aiuta a studiare le variazioni di prezzo, confrontare oggetti, seguire l’attività del mercato e individuare possibili opportunità di acquisto o vendita.', 'Gli strumenti includono la tabella principale, il profilo personale, Smart Buy, Sell Advisor e scanner specializzati.', 'Indicatori, previsioni e calcoli sono informativi. Verifica prezzo e disponibilità prima di ogni scambio.', 'FrameAnalytics non è affiliato a Digital Extremes o Warframe Market e non li rappresenta. Nomi e materiali appartengono ai rispettivi titolari.', 'Il servizio è in fase di test. Interfaccia, calcoli e funzioni possono cambiare.')] },
      faq: { title: 'Domande frequenti', sections: [section('Da dove provengono i prezzi?', 'FrameAnalytics usa dati di mercato disponibili e statistiche accumulate di Warframe Market. Non stabilisce prezzi né gestisce offerte.'), section('Perché il prezzo può differire da un’offerta attuale?', 'Un ordine attivo può cambiare o essere rimosso tra gli aggiornamenti. Controlla sempre il prezzo nella pagina dell’offerta.'), section('Che cos’è il profitto potenziale?', 'È la differenza calcolata tra il prezzo attuale e un riferimento scelto. Non garantisce acquisto o vendita a quel prezzo.'), section('Che cosa fanno Smart Buy e Sell Advisor?', 'Analizzano le offerte e preparano consigli. Non scambiano, inviano messaggi o modificano ordini automaticamente.'), section('Perché una scansione può richiedere tempo?', 'Alcune operazioni sono sequenziali o attendono in coda per mantenere stabili servizio e fonti.'), section('Serve la password di Warframe Market?', 'No. FrameAnalytics non deve mai chiedere password, codici monouso o altri segreti degli account.'), section('Dove vengono salvati gli acquisti?', 'Dopo l’accesso possono essere salvati nel profilo FrameAnalytics. Le preferenze visive e delle tabelle possono restare nel browser.'), section('Come segnalo un errore?', 'Apri Contatti e indica pagina, passaggi e testo dell’errore. Non allegare password, token o altri segreti.')] },
      privacy: { title: 'Informativa sulla privacy', updated: 'Aggiornata il 1° settembre 2026.', intro: 'FrameAnalytics tratta solo le informazioni necessarie al sito, agli account e alle funzioni utente.', sections: [section('Dati trattati', 'Possono includere e-mail, dati di accesso, impostazioni di profilo e interfaccia, acquisti salvati, autorizzazioni e informazioni aggiunte al profilo. I dati tecnici possono essere trattati temporaneamente per sicurezza e diagnostica. Non sono richiesti segreti di account esterni.'), section('Utilizzo', 'I dati servono per accesso e protezione, profili e impostazioni, strumenti personali, prevenzione degli abusi e diagnosi degli errori.'), section('Dati del browser', 'Lingua, tema, tabelle e altre preferenze possono essere salvati nel browser e rimossi dalle impostazioni.'), section('Terze parti', 'I fornitori tecnici ricevono solo i dati necessari a ospitare e gestire il sito. I siti esterni applicano le proprie regole.'), section('Conservazione', 'I dati dell’account restano fino alla cancellazione o all’elaborazione di una richiesta verificata. I log tecnici solo per il tempo necessario a sicurezza e diagnostica.'), section('I tuoi dati', 'Richiedi accesso, correzione o cancellazione con un messaggio Discord privato a `azulor`. Può essere necessaria una verifica.')] },
      terms: { title: 'Condizioni d’uso', updated: 'Aggiornate il 1° settembre 2026.', intro: 'Usando FrameAnalytics accetti queste condizioni.', sections: [section('Scopo', 'FrameAnalytics offre analisi e strumenti di supporto per il mercato Warframe. Prezzi, previsioni, consigli e profitti potenziali sono indicativi e non garantiscono scambi o guadagni.'), section('Responsabilità', 'Decidi tu se comprare o vendere e devi verificare prezzo, quantità, oggetto e nome del giocatore. FrameAnalytics non partecipa allo scambio e non custodisce oggetti o Platinum.'), section('Account', 'Sei responsabile dell’accesso. Non usare credenziali altrui, aggirare controlli o cercare funzioni non concesse.'), section('Uso consentito', 'Non creare carico eccessivo, aggirare protezioni, accedere senza autorizzazione o usare il servizio per inganno, frode o violazioni esterne.'), section('Risorse esterne', 'FrameAnalytics non controlla disponibilità, contenuti o regole dei siti esterni collegati.'), section('Modifiche e disponibilità', 'Durante i test le funzioni possono cambiare, essere disattivate o limitate. Anche queste condizioni possono essere aggiornate.'), section('Contatti', 'Invia domande con un messaggio Discord privato a `azulor`.')] },
      contact: { title: 'Contatti', intro: 'Per domande su FrameAnalytics invia un messaggio Discord privato a `azulor`.', sections: [section('Segnala un errore', 'Indica pagina, data e ora approssimative, passaggi, testo completo e uno screenshot utile. Non inviare password, codici, token o altri segreti.'), section('Proponi una funzione', 'Descrivi il problema e il risultato atteso. Non serve un progetto dell’interfaccia completo.'), section('Problema con l’account', 'Indica l’e-mail dell’account e descrivi brevemente il problema. Cancellazione o ripristino possono richiedere prova di proprietà.'), section('Sicurezza', 'Non pubblicare dettagli sulle vulnerabilità. Inviali privatamente su Discord a `azulor`.')] },
    },
  },
  sv: {
    back: 'Startsida', navigationLabel: 'Information om FrameAnalytics',
    nav: { about: 'Om projektet', faq: 'Vanliga frågor', privacy: 'Integritet', terms: 'Användarvillkor', contact: 'Kontakt' },
    pages: {
      about: { title: 'Om projektet', intro: 'FrameAnalytics är en oberoende analystjänst för Warframe-spelare.', sections: [section(undefined, 'Tjänsten hjälper dig att studera prisförändringar, jämföra föremål, följa marknadsaktivitet och hitta möjliga köp- eller säljtillfällen.', 'Verktygen omfattar huvudtabellen, personlig profil, Smart Buy, Sell Advisor och specialiserade skannrar.', 'Alla indikatorer, prognoser och beräkningar är endast information. Kontrollera pris och tillgänglighet före handel.', 'FrameAnalytics är inte kopplat till Digital Extremes eller Warframe Market och representerar dem inte. Namn och material tillhör respektive rättighetsinnehavare.', 'Tjänsten testas. Gränssnitt, beräkningar och funktioner kan ändras.')] },
      faq: { title: 'Vanliga frågor', sections: [section('Varifrån kommer priserna?', 'FrameAnalytics använder tillgängliga marknadsdata och samlad statistik från Warframe Market. Tjänsten sätter inte priser eller hanterar erbjudanden.'), section('Varför kan priset skilja sig från ett aktuellt erbjudande?', 'En aktiv order kan ändras eller tas bort mellan uppdateringar. Kontrollera priset på erbjudandesidan före handel.'), section('Vad betyder potentiell vinst?', 'Det är den beräknade skillnaden mellan aktuellt pris och en vald referens. Det garanterar inte köp eller försäljning till priset.'), section('Vad gör Smart Buy och Sell Advisor?', 'De analyserar erbjudanden och ger rekommendationer. De handlar inte, skickar inte meddelanden och ändrar inte order automatiskt.'), section('Varför kan en skanning ta tid?', 'Vissa åtgärder körs i följd eller väntar i kö för att hålla tjänsten och datakällorna stabila.'), section('Behövs mitt Warframe Market-lösenord?', 'Nej. FrameAnalytics ska aldrig be om lösenord, engångskoder eller andra kontouppgifter.'), section('Var sparas mina köp?', 'Efter inloggning kan de sparas i din FrameAnalytics-profil. Utseende- och tabellinställningar kan också finnas kvar i webbläsaren.'), section('Hur rapporterar jag ett fel?', 'Öppna Kontakt och ange sida, steg och feltext. Bifoga inte lösenord, token eller andra hemligheter.')] },
      privacy: { title: 'Integritetspolicy', updated: 'Uppdaterad: 1 september 2026.', intro: 'FrameAnalytics behandlar bara information som behövs för webbplatsen, konton och användarfunktioner.', sections: [section('Data som kan behandlas', 'Det kan vara e-post, inloggningsdata, profil- och gränssnittsinställningar, sparade köp, behörigheter och profiluppgifter. Tekniska data kan behandlas tillfälligt för säkerhet och diagnostik. Hemligheter från externa konton begärs inte.'), section('Användning', 'Data används för inloggning och skydd, profiler och inställningar, personliga verktyg, missbruksförebyggande och feldiagnostik.'), section('Webbläsardata', 'Språk, tema, tabellinställningar och andra val kan sparas i webbläsaren och tas bort i dess inställningar.'), section('Tredje parter', 'Tekniska leverantörer får bara data som krävs för drift och hosting. Externa webbplatser har egna regler.'), section('Lagring', 'Kontodata lagras tills kontot tas bort eller en verifierad begäran behandlas. Tekniska loggar bara så länge säkerhet och diagnostik kräver.'), section('Dina data', 'Begär åtkomst, rättelse eller radering med ett privat Discord-meddelande till `azulor`. Kontot kan behöva verifieras.')] },
      terms: { title: 'Användarvillkor', updated: 'Uppdaterade: 1 september 2026.', intro: 'Genom att använda FrameAnalytics godkänner du dessa villkor.', sections: [section('Syfte', 'FrameAnalytics erbjuder analys och hjälpverktyg för Warframe-marknaden. Priser, prognoser, råd och potentiell vinst är uppskattningar utan garanti för affär eller vinst.'), section('Ansvar', 'Du beslutar om köp och försäljning och ska kontrollera pris, mängd, föremål och spelarens namn. FrameAnalytics är inte part i affären och förvarar inte föremål eller Platinum.'), section('Konto', 'Du ansvarar för åtkomsten. Använd inte andras uppgifter, kringgå inte kontroller och försök inte få obehöriga funktioner.'), section('Tillåten användning', 'Skapa inte överdriven belastning, kringgå skydd, få obehörig åtkomst eller använd tjänsten för bedrägeri eller brott mot externa regler.'), section('Externa resurser', 'FrameAnalytics styr inte tillgänglighet, innehåll eller regler på länkade externa webbplatser.'), section('Ändringar och tillgänglighet', 'Under testning kan funktioner ändras, stängas av eller begränsas. Villkoren kan också uppdateras.'), section('Kontakt', 'Skicka frågor privat på Discord till `azulor`.')] },
      contact: { title: 'Kontakt', intro: 'För frågor om FrameAnalytics, skicka ett privat Discord-meddelande till `azulor`.', sections: [section('Rapportera ett fel', 'Ange sida, ungefärligt datum och tid, steg, fullständig feltext och en hjälpsam bild. Skicka inte lösenord, koder, token eller andra hemligheter.'), section('Föreslå en funktion', 'Beskriv problemet och önskat resultat. En färdig gränssnittsdesign krävs inte.'), section('Kontofråga', 'Ange kontots e-post och beskriv problemet kort. Radering eller återställning kan kräva bevis på ägarskap.'), section('Säkerhet', 'Publicera inte sårbarhetsdetaljer. Skicka dem privat på Discord till `azulor`.')] },
    },
  },
  cs: {
    back: 'Domů', navigationLabel: 'Informace o FrameAnalytics',
    nav: { about: 'O projektu', faq: 'Časté dotazy', privacy: 'Soukromí', terms: 'Podmínky použití', contact: 'Kontakt' },
    pages: {
      about: { title: 'O projektu', intro: 'FrameAnalytics je nezávislá analytická služba pro hráče Warframe.', sections: [section(undefined, 'Pomáhá sledovat změny cen, porovnávat předměty, pozorovat aktivitu trhu a hledat zajímavé možnosti nákupu či prodeje.', 'Nástroje zahrnují hlavní tabulku, osobní profil, Smart Buy, Sell Advisor a specializované skenery.', 'Všechny ukazatele, prognózy a výpočty jsou informativní. Před obchodem ověřte cenu a dostupnost nabídky.', 'FrameAnalytics není spojen s Digital Extremes ani Warframe Market a nezastupuje je. Názvy a materiály patří příslušným vlastníkům.', 'Služba je ve fázi testování. Rozhraní, výpočty a funkce se mohou měnit.')] },
      faq: { title: 'Časté dotazy', sections: [section('Odkud pocházejí ceny?', 'FrameAnalytics používá dostupná tržní data a statistiky Warframe Market. Ceny neurčuje ani nespravuje nabídky.'), section('Proč se cena může lišit od aktuální nabídky?', 'Aktivní objednávka může být mezi aktualizacemi změněna nebo odstraněna. Před obchodem ověřte cenu na stránce nabídky.'), section('Co znamená potenciální zisk?', 'Jde o vypočtený rozdíl mezi aktuální cenou a zvolenou referencí. Nezaručuje nákup ani prodej za tuto cenu.'), section('Co dělají Smart Buy a Sell Advisor?', 'Analyzují nabídky a připravují doporučení. Neobchodují, neposílají zprávy ani automaticky nemění objednávky.'), section('Proč může skenování trvat?', 'Některé operace běží postupně nebo čekají ve frontě kvůli stabilitě služby a zdrojů.'), section('Je potřeba heslo Warframe Market?', 'Ne. FrameAnalytics nikdy nemá vyžadovat hesla, jednorázové kódy ani jiná tajemství účtů.'), section('Kde se ukládají nákupy?', 'Po přihlášení mohou být uloženy v profilu FrameAnalytics. Nastavení vzhledu a tabulek může zůstat i v prohlížeči.'), section('Jak nahlásím chybu?', 'Otevřete Kontakt a uveďte stránku, kroky a text chyby. Nepřikládejte hesla, tokeny ani jiná tajemství.')] },
      privacy: { title: 'Zásady ochrany soukromí', updated: 'Aktualizováno: 1. září 2026.', intro: 'FrameAnalytics zpracovává pouze informace potřebné pro web, účty a uživatelské funkce.', sections: [section('Zpracovávaná data', 'Mohou zahrnovat e-mail, přihlašovací data, nastavení profilu a rozhraní, uložené nákupy, oprávnění a údaje v profilu. Technická data mohou být dočasně zpracována pro bezpečnost a diagnostiku. Tajemství externích účtů nejsou vyžadována.'), section('Použití', 'Data slouží k přihlášení a ochraně, profilům a nastavení, osobním nástrojům, prevenci zneužití a diagnostice chyb.'), section('Data prohlížeče', 'Jazyk, motiv, tabulky a další preference mohou být uloženy v prohlížeči a odstraněny v jeho nastavení.'), section('Třetí strany', 'Techničtí poskytovatelé dostávají jen data nutná pro hosting a provoz. Externí weby mají vlastní pravidla.'), section('Uchovávání', 'Data účtu se uchovávají do jeho odstranění nebo zpracování ověřené žádosti. Technické logy jen po dobu nutnou pro bezpečnost a diagnostiku.'), section('Vaše data', 'O přístup, opravu nebo odstranění požádejte soukromou zprávou na Discordu uživateli `azulor`. Může být nutné ověření účtu.')] },
      terms: { title: 'Podmínky použití', updated: 'Aktualizováno: 1. září 2026.', intro: 'Používáním FrameAnalytics souhlasíte s těmito podmínkami.', sections: [section('Účel', 'FrameAnalytics poskytuje analýzy a pomocné nástroje pro trh Warframe. Ceny, prognózy, doporučení a potenciální zisk jsou odhady bez záruky obchodu či zisku.'), section('Odpovědnost', 'O nákupu či prodeji rozhodujete sami a ověřujete cenu, množství, předmět a jméno hráče. FrameAnalytics není stranou obchodu a nedrží předměty ani Platinum.'), section('Účet', 'Odpovídáte za přístup. Nepoužívejte cizí údaje, neobcházejte omezení ani neusilujte o nepřidělené funkce.'), section('Přijatelné použití', 'Nevytvářejte nadměrnou zátěž, neobcházejte ochranu, nezískávejte neoprávněný přístup a nepoužívejte službu k podvodu či porušení cizích pravidel.'), section('Externí zdroje', 'FrameAnalytics nekontroluje dostupnost, obsah ani pravidla propojených externích webů.'), section('Změny a dostupnost', 'Během testování se funkce mohou měnit, vypínat nebo omezovat. Podmínky mohou být rovněž aktualizovány.'), section('Kontakt', 'Dotazy pošlete soukromě na Discordu uživateli `azulor`.')] },
      contact: { title: 'Kontakt', intro: 'S dotazy k FrameAnalytics napište soukromě na Discordu uživateli `azulor`.', sections: [section('Nahlásit chybu', 'Uveďte stránku, přibližné datum a čas, kroky, celý text chyby a vhodný snímek. Neposílejte hesla, kódy, tokeny ani tajemství.'), section('Navrhnout funkci', 'Popište problém a očekávaný výsledek. Hotový návrh rozhraní není nutný.'), section('Dotaz k účtu', 'Uveďte e-mail účtu a stručně popište problém. Odstranění či obnovení může vyžadovat ověření vlastnictví.'), section('Bezpečnost', 'Nezveřejňujte podrobnosti zranitelnosti. Pošlete je soukromě přes Discord uživateli `azulor`.')] },
    },
  },
  ja: {
    back: 'ホーム', navigationLabel: 'FrameAnalytics の情報',
    nav: { about: 'プロジェクトについて', faq: 'よくある質問', privacy: 'プライバシー', terms: '利用規約', contact: 'お問い合わせ' },
    pages: {
      about: { title: 'プロジェクトについて', intro: 'FrameAnalytics は Warframe プレイヤー向けの独立した分析サービスです。', sections: [section(undefined, '価格変動の調査、アイテム比較、市場活動の追跡、購入・販売候補の発見を支援します。', '主な分析表、個人プロフィール、Smart Buy、Sell Advisor、専用スキャナーを利用できます。', '指標、予測、計算はすべて参考情報です。取引前に価格と出品状況を必ず確認してください。', 'FrameAnalytics は Digital Extremes または Warframe Market と提携せず、両者を代表しません。名称と素材の権利は各権利者に帰属します。', 'サービスはテスト中であり、画面、計算方法、機能は変更される場合があります。')] },
      faq: { title: 'よくある質問', sections: [section('価格の出所は？', 'FrameAnalytics は利用可能な市場データと Warframe Market の蓄積統計を使用します。価格設定や出品管理は行いません。'), section('現在の出品価格と異なるのはなぜ？', '更新の間に注文が変更または削除されることがあります。取引前に出品ページで価格を確認してください。'), section('潜在利益とは？', '現在価格と選択した基準値との差の計算結果です。その価格での購入・販売を保証しません。'), section('Smart Buy と Sell Advisor は何をしますか？', '出品を分析して推奨を作成します。取引、メッセージ送信、注文の自動変更は行いません。'), section('スキャンに時間がかかるのはなぜ？', 'サービスとデータ元を安定させるため、一部の処理は順番に実行されるか待機列に入ります。'), section('Warframe Market のパスワードは必要？', 'いいえ。FrameAnalytics がパスワード、ワンタイムコード、その他の秘密情報を求めることはありません。'), section('購入履歴はどこに保存されますか？', 'ログイン後は FrameAnalytics プロフィールに保存される場合があります。表示や表の設定はブラウザーにも保存されます。'), section('不具合の報告方法は？', 'お問い合わせページで、対象ページ、手順、エラー全文を知らせてください。パスワードやトークンは添付しないでください。')] },
      privacy: { title: 'プライバシーポリシー', updated: '更新日：2026年9月1日。', intro: 'FrameAnalytics はサイト、アカウント、ユーザー機能の運用に必要な情報のみを処理します。', sections: [section('処理される可能性があるデータ', 'メールアドレス、ログイン情報、プロフィールと画面の設定、保存した購入、権限、プロフィールに追加した情報が含まれます。安全対策と診断のため技術情報を一時的に処理する場合があります。外部アカウントの秘密情報は求めません。'), section('利用目的', 'ログインと保護、プロフィールと設定、個人用ツール、不正利用防止、エラー診断に使用します。'), section('ブラウザーデータ', '言語、テーマ、表などの設定はブラウザーに保存され、設定画面から削除できます。'), section('外部サービス', '技術提供者には運用に必要なデータのみが渡ります。外部サイトには各サイトの規則が適用されます。'), section('保存期間', 'アカウントデータはアカウント削除または確認済み削除依頼の処理まで保存します。技術ログは安全対策と診断に必要な期間のみ保存します。'), section('データに関する依頼', 'アクセス、訂正、削除は Discord の `azulor` へ個人メッセージで依頼してください。本人確認が必要な場合があります。')] },
      terms: { title: '利用規約', updated: '更新日：2026年9月1日。', intro: 'FrameAnalytics を使用すると本規約に同意したものとみなされます。', sections: [section('目的', 'FrameAnalytics は Warframe 市場の分析と補助ツールを提供します。価格、予測、推奨、潜在利益は目安であり、取引や利益を保証しません。'), section('利用者の責任', '購入・販売は利用者が判断し、価格、数量、アイテム、相手名を確認します。FrameAnalytics は取引当事者ではなく、アイテムや Platinum を保管しません。'), section('アカウント', 'アクセス管理は利用者の責任です。他人の資格情報の使用、制限回避、未許可機能の取得は禁止です。'), section('許容される利用', '過剰な負荷、保護の回避、不正アクセス、欺瞞・詐欺・外部規則違反への利用を禁止します。'), section('外部リソース', 'リンク先外部サイトの可用性、内容、規則を FrameAnalytics は管理しません。'), section('変更と提供状況', 'テスト中は機能が変更、停止、限定される場合があります。規約も更新される場合があります。'), section('連絡先', '質問は Discord の `azulor` へ個人メッセージで送ってください。')] },
      contact: { title: 'お問い合わせ', intro: 'FrameAnalytics に関する質問は Discord の `azulor` へ個人メッセージで送ってください。', sections: [section('不具合報告', '対象ページ、おおよその日時、手順、エラー全文、必要に応じて画像を添えてください。パスワード、コード、トークンなどは送らないでください。'), section('機能提案', '解決したい問題と期待する結果を説明してください。完成した画面案は不要です。'), section('アカウントの質問', 'アカウントのメールアドレスと問題の概要を知らせてください。削除や復元では所有確認が必要な場合があります。'), section('セキュリティ', '脆弱性の詳細を公開せず、Discord の `azulor` へ個人メッセージで送ってください。')] },
    },
  },
  ko: {
    back: '홈', navigationLabel: 'FrameAnalytics 정보',
    nav: { about: '프로젝트 소개', faq: '자주 묻는 질문', privacy: '개인정보 처리방침', terms: '이용 약관', contact: '문의' },
    pages: {
      about: { title: '프로젝트 소개', intro: 'FrameAnalytics는 Warframe 플레이어를 위한 독립적인 분석 서비스입니다.', sections: [section(undefined, '가격 변화를 살펴보고, 아이템을 비교하고, 시장 활동을 추적하며, 유망한 구매 또는 판매 기회를 찾도록 돕습니다.', '주요 분석표, 개인 프로필, Smart Buy, Sell Advisor, 전문 스캐너를 제공합니다.', '모든 지표, 예측, 계산은 정보 제공용입니다. 거래 전에 가격과 제안의 유효성을 직접 확인하세요.', 'FrameAnalytics는 Digital Extremes 또는 Warframe Market과 제휴하거나 이를 대표하지 않습니다. 관련 명칭과 자료의 권리는 각 권리자에게 있습니다.', '서비스는 테스트 중이며 인터페이스, 계산 방식, 기능이 변경될 수 있습니다.')] },
      faq: { title: '자주 묻는 질문', sections: [section('가격은 어디에서 오나요?', 'FrameAnalytics는 이용 가능한 시장 데이터와 Warframe Market 누적 통계를 사용합니다. 가격을 정하거나 제안을 관리하지 않습니다.'), section('현재 제안과 가격이 다른 이유는?', '업데이트 사이에 활성 주문이 변경되거나 삭제될 수 있습니다. 거래 전 제안 페이지에서 현재 가격을 확인하세요.'), section('잠재 수익이란?', '현재 가격과 선택한 기준값의 계산된 차이입니다. 해당 가격의 구매나 판매를 보장하지 않습니다.'), section('Smart Buy와 Sell Advisor는 무엇을 하나요?', '제안을 분석하고 권장 사항을 준비합니다. 거래, 메시지 전송, 주문 자동 변경은 하지 않습니다.'), section('스캔에 시간이 걸리는 이유는?', '서비스와 데이터 원본의 안정성을 위해 일부 작업은 순차 실행되거나 대기열에서 기다립니다.'), section('Warframe Market 비밀번호가 필요한가요?', '아니요. FrameAnalytics는 비밀번호, 일회용 코드 또는 계정 비밀 정보를 요구해서는 안 됩니다.'), section('구매 내역은 어디에 저장되나요?', '로그인 후 FrameAnalytics 프로필에 저장될 수 있습니다. 표시 및 표 설정은 브라우저에도 남을 수 있습니다.'), section('오류는 어떻게 신고하나요?', '문의 페이지에서 해당 페이지, 재현 단계, 오류 전문을 알려 주세요. 비밀번호나 토큰은 첨부하지 마세요.')] },
      privacy: { title: '개인정보 처리방침', updated: '업데이트: 2026년 9월 1일.', intro: 'FrameAnalytics는 사이트, 계정, 사용자 기능 운영에 필요한 정보만 처리합니다.', sections: [section('처리될 수 있는 데이터', '이메일, 로그인 데이터, 프로필 및 화면 설정, 저장된 구매, 권한, 프로필에 추가한 정보가 포함될 수 있습니다. 보안과 진단을 위해 기술 데이터를 일시 처리할 수 있습니다. 외부 계정의 비밀 정보는 요구하지 않습니다.'), section('사용 목적', '로그인과 계정 보호, 프로필과 설정, 개인 도구, 악용 방지, 오류 진단에 사용합니다.'), section('브라우저 데이터', '언어, 테마, 표 설정과 기타 선택 항목은 브라우저에 저장되고 브라우저 설정에서 삭제할 수 있습니다.'), section('제3자 서비스', '기술 제공자는 호스팅과 운영에 필요한 데이터만 받습니다. 외부 사이트에는 자체 정책이 적용됩니다.'), section('보관 기간', '계정 데이터는 계정 삭제 또는 확인된 삭제 요청 처리까지 보관합니다. 기술 로그는 보안과 진단에 필요한 기간만 보관합니다.'), section('데이터 요청', '접근, 수정, 삭제는 Discord의 `azulor`에게 개인 메시지로 요청하세요. 계정 소유 확인이 필요할 수 있습니다.')] },
      terms: { title: '이용 약관', updated: '업데이트: 2026년 9월 1일.', intro: 'FrameAnalytics를 사용하면 본 약관에 동의하는 것입니다.', sections: [section('목적', 'FrameAnalytics는 Warframe 시장 분석과 보조 도구를 제공합니다. 가격, 예측, 권장 사항, 잠재 수익은 참고값이며 거래나 수익을 보장하지 않습니다.'), section('사용자 책임', '구매와 판매는 사용자가 결정하고 가격, 수량, 아이템, 상대 이름을 확인해야 합니다. FrameAnalytics는 거래 당사자가 아니며 아이템이나 Platinum을 보관하지 않습니다.'), section('계정', '접근 관리는 사용자 책임입니다. 타인의 자격 증명 사용, 접근 제한 우회, 허용되지 않은 기능 획득을 금지합니다.'), section('허용되는 사용', '과도한 부하, 보호 우회, 무단 접근, 기만·사기·외부 규칙 위반에 서비스를 사용하지 마세요.'), section('외부 리소스', 'FrameAnalytics는 연결된 외부 사이트의 가용성, 콘텐츠, 규칙을 통제하지 않습니다.'), section('변경 및 가용성', '테스트 중 기능이 변경, 중단, 제한될 수 있으며 약관도 업데이트될 수 있습니다.'), section('문의', '질문은 Discord의 `azulor`에게 개인 메시지로 보내세요.')] },
      contact: { title: '문의', intro: 'FrameAnalytics 관련 문의는 Discord의 `azulor`에게 개인 메시지로 보내세요.', sections: [section('오류 신고', '페이지, 대략적인 날짜와 시간, 재현 단계, 오류 전문, 필요한 화면 이미지를 포함하세요. 비밀번호, 코드, 토큰 등은 보내지 마세요.'), section('기능 제안', '해결하려는 문제와 기대 결과를 설명하세요. 완성된 인터페이스 설계는 필요하지 않습니다.'), section('계정 문의', '계정 이메일과 문제를 간단히 적어 주세요. 삭제 또는 복원 시 소유 확인이 필요할 수 있습니다.'), section('보안', '취약점 세부 정보를 공개하지 말고 Discord의 `azulor`에게 개인 메시지로 보내세요.')] },
    },
  },
  'zh-hans': {
    back: '首页', navigationLabel: 'FrameAnalytics 信息',
    nav: { about: '关于项目', faq: '常见问题', privacy: '隐私政策', terms: '使用条款', contact: '联系我们' },
    pages: {
      about: { title: '关于项目', intro: 'FrameAnalytics 是面向 Warframe 玩家的独立分析服务。', sections: [section(undefined, '它帮助研究价格变化、比较物品、跟踪市场活动，并寻找可能值得关注的买卖机会。', '可用工具包括主分析表、个人资料、Smart Buy、Sell Advisor 和专用扫描器。', '所有指标、预测和计算仅供参考。交易前请自行核实价格和订单是否仍然有效。', 'FrameAnalytics 与 Digital Extremes 或 Warframe Market 无关联，也不代表它们。相关名称和素材归各自权利人所有。', '服务仍在测试中，界面、计算方式和可用功能可能会变化。')] },
      faq: { title: '常见问题', sections: [section('价格来自哪里？', 'FrameAnalytics 使用可用市场数据和 Warframe Market 的累计统计，不制定价格，也不管理玩家订单。'), section('为什么价格可能与当前订单不同？', '活跃订单可能在两次更新之间被修改或删除。交易前请在订单页面核实当前价格。'), section('什么是潜在利润？', '它是当前价格与所选参考值之间的计算差额，不保证能按该价格买入或卖出。'), section('Smart Buy 和 Sell Advisor 做什么？', '它们分析订单并生成建议，不会交易、向玩家发送消息或自动修改订单。'), section('为什么扫描有时需要等待？', '部分操作会依次执行或进入队列，以保持服务和数据源稳定。'), section('需要 Warframe Market 密码吗？', '不需要。FrameAnalytics 不应索要密码、一次性验证码或任何其他账户机密。'), section('我的购买记录保存在哪里？', '登录后可保存在 FrameAnalytics 个人资料中。外观和表格设置也可能保存在当前浏览器。'), section('如何报告错误？', '打开“联系我们”页面，提供页面、操作步骤和完整错误文本。请勿附带密码、令牌等机密。')] },
      privacy: { title: '隐私政策', updated: '更新日期：2026 年 9 月 1 日。', intro: 'FrameAnalytics 仅处理网站、账户和用户功能运行所需的信息。', sections: [section('可能处理的数据', '可能包括电子邮件、登录数据、个人资料和界面设置、保存的购买记录、权限以及用户添加到资料中的信息。安全和诊断需要时会临时处理技术请求数据。不会索要第三方账户机密。'), section('使用方式', '数据用于登录和账户保护、保存资料与设置、运行个人工具、防止滥用及诊断错误。'), section('浏览器数据', '语言、主题、表格设置和其他偏好可能保存在浏览器中，并可在浏览器设置中删除。'), section('第三方服务', '技术服务商只会获得托管和运行所需的数据。访问外部网站时适用该网站自己的政策。'), section('保留期限', '账户数据保留到删除账户或处理已确认的删除请求为止。技术日志仅在安全和诊断所需期间保留。'), section('您的数据', '如需访问、更正或删除，请在 Discord 私信 `azulor`。处理前可能需要验证账户所有权。')] },
      terms: { title: '使用条款', updated: '更新日期：2026 年 9 月 1 日。', intro: '使用 FrameAnalytics 即表示您同意这些条款。', sections: [section('服务目的', 'FrameAnalytics 提供 Warframe 市场分析和辅助工具。价格、预测、建议和潜在利润均为估算，不保证交易成功或获得利润。'), section('用户责任', '买卖决定由用户自行作出，并须核实价格、数量、物品和交易者名称。FrameAnalytics 不是交易一方，也不保管物品或 Platinum。'), section('账户', '用户须对账户访问负责。禁止使用他人凭据、绕过访问限制或获取未授权功能。'), section('可接受的使用', '禁止造成过度负载、绕过保护、未经授权访问，或将服务用于欺骗、诈骗或违反第三方规则。'), section('外部资源', 'FrameAnalytics 不控制链接的外部网站的可用性、内容或规则。'), section('变更与可用性', '测试期间功能可能改变、暂停或限制。条款也可能更新。'), section('联系', '相关问题请在 Discord 私信 `azulor`。')] },
      contact: { title: '联系我们', intro: '关于 FrameAnalytics 的问题，请在 Discord 私信 `azulor`。', sections: [section('报告错误', '请提供出错页面、大致日期和时间、操作步骤、完整错误文本以及有帮助的截图。请勿发送密码、验证码、访问令牌等机密。'), section('建议功能', '请描述您想解决的问题和预期结果，无需提供完整界面方案。'), section('账户问题', '请提供账户邮箱并简要说明问题。删除或恢复数据可能需要验证账户所有权。'), section('安全问题', '请勿公开漏洞详情，请在 Discord 私信 `azulor`。')] },
    },
  },
  'zh-hant': {
    back: '首頁', navigationLabel: 'FrameAnalytics 資訊',
    nav: { about: '關於專案', faq: '常見問題', privacy: '隱私政策', terms: '使用條款', contact: '聯絡我們' },
    pages: {
      about: { title: '關於專案', intro: 'FrameAnalytics 是面向 Warframe 玩家的獨立分析服務。', sections: [section(undefined, '它協助研究價格變化、比較物品、追蹤市場活動，並尋找可能值得關注的買賣機會。', '可用工具包括主要分析表、個人資料、Smart Buy、Sell Advisor 和專用掃描器。', '所有指標、預測和計算僅供參考。交易前請自行確認價格及訂單是否仍然有效。', 'FrameAnalytics 與 Digital Extremes 或 Warframe Market 無關聯，也不代表它們。相關名稱與素材歸各自權利人所有。', '服務仍在測試中，介面、計算方式及可用功能可能變更。')] },
      faq: { title: '常見問題', sections: [section('價格來自哪裡？', 'FrameAnalytics 使用可用市場資料及 Warframe Market 的累積統計，不制定價格，也不管理玩家訂單。'), section('為什麼價格可能與目前訂單不同？', '活躍訂單可能在兩次更新之間被修改或刪除。交易前請在訂單頁確認目前價格。'), section('什麼是潛在利潤？', '它是目前價格與所選參考值之間的計算差額，不保證能按該價格買入或賣出。'), section('Smart Buy 和 Sell Advisor 做什麼？', '它們分析訂單並產生建議，不會交易、向玩家傳送訊息或自動修改訂單。'), section('為什麼掃描有時需要等待？', '部分操作會依序執行或進入佇列，以維持服務及資料來源穩定。'), section('需要 Warframe Market 密碼嗎？', '不需要。FrameAnalytics 不應索取密碼、一次性驗證碼或任何其他帳戶機密。'), section('我的購買記錄存在哪裡？', '登入後可儲存在 FrameAnalytics 個人資料中。外觀及表格設定也可能保存在目前瀏覽器。'), section('如何回報錯誤？', '開啟「聯絡我們」頁面，提供頁面、操作步驟及完整錯誤文字。請勿附上密碼、權杖等機密。')] },
      privacy: { title: '隱私政策', updated: '更新日期：2026 年 9 月 1 日。', intro: 'FrameAnalytics 僅處理網站、帳戶及使用者功能運作所需的資訊。', sections: [section('可能處理的資料', '可能包括電子郵件、登入資料、個人資料及介面設定、保存的購買記錄、權限，以及使用者加入資料中的資訊。安全與診斷需要時會暫時處理技術請求資料。不會索取第三方帳戶機密。'), section('使用方式', '資料用於登入及帳戶保護、保存資料與設定、執行個人工具、防止濫用及診斷錯誤。'), section('瀏覽器資料', '語言、主題、表格設定及其他偏好可能保存在瀏覽器中，並可在瀏覽器設定中刪除。'), section('第三方服務', '技術服務商只會取得託管及運作所需的資料。造訪外部網站時適用該網站自己的政策。'), section('保留期限', '帳戶資料保留至刪除帳戶或處理已確認的刪除要求。技術日誌僅在安全及診斷所需期間保留。'), section('您的資料', '如需存取、更正或刪除，請在 Discord 私訊 `azulor`。處理前可能需要驗證帳戶所有權。')] },
      terms: { title: '使用條款', updated: '更新日期：2026 年 9 月 1 日。', intro: '使用 FrameAnalytics 即表示您同意這些條款。', sections: [section('服務目的', 'FrameAnalytics 提供 Warframe 市場分析及輔助工具。價格、預測、建議及潛在利潤均為估算，不保證交易成功或獲得利潤。'), section('使用者責任', '買賣決定由使用者自行作出，並須確認價格、數量、物品及交易者名稱。FrameAnalytics 不是交易一方，也不保管物品或 Platinum。'), section('帳戶', '使用者須對帳戶存取負責。禁止使用他人憑證、繞過存取限制或取得未授權功能。'), section('可接受的使用', '禁止造成過度負載、繞過保護、未經授權存取，或將服務用於欺騙、詐騙或違反第三方規則。'), section('外部資源', 'FrameAnalytics 不控制連結之外部網站的可用性、內容或規則。'), section('變更與可用性', '測試期間功能可能變更、暫停或限制。條款也可能更新。'), section('聯絡', '相關問題請在 Discord 私訊 `azulor`。')] },
      contact: { title: '聯絡我們', intro: '關於 FrameAnalytics 的問題，請在 Discord 私訊 `azulor`。', sections: [section('回報錯誤', '請提供出錯頁面、大致日期與時間、操作步驟、完整錯誤文字及有幫助的截圖。請勿傳送密碼、驗證碼、存取權杖等機密。'), section('建議功能', '請描述您想解決的問題及預期結果，無須提供完整介面方案。'), section('帳戶問題', '請提供帳戶電子郵件並簡述問題。刪除或還原資料可能需要驗證帳戶所有權。'), section('安全問題', '請勿公開漏洞詳情，請在 Discord 私訊 `azulor`。')] },
    },
  },
} satisfies Record<Locale, InfoLocaleCopy>

const renderInlineCode = (value: string) => {
  const parts = value.split('`')
  return parts.map((part, index) => index % 2 ? <code key={`${part}-${index}`}>{part}</code> : part)
}

export const InfoPage = ({ kind, locale }: { kind: InfoPageKind; locale: Locale }) => {
  const language = infoCopy[locale]
  const page = language.pages[kind]
  return <main className="app-shell info-page-shell">
    <div className="detail-navigation">
      <a className="brand-plate detail-brand" href="/" aria-label={`FrameAnalytics — ${language.back}`}><img src="/assets/frameanalytics-logo.webp" alt="FrameAnalytics"/></a>
      <a className="back-button" href="/">← {language.back}</a>
    </div>
    <article className="panel info-document">
      <header><h1>{page.title}</h1>{page.intro ? <p>{renderInlineCode(page.intro)}</p> : null}{page.updated ? <small>{page.updated}</small> : null}</header>
      <div className="info-sections">{page.sections.map((item, index) => <section key={`${item.title || 'section'}-${index}`}>
        {item.title ? <h2>{item.title}</h2> : null}
        {item.paragraphs.map((paragraph, paragraphIndex) => <p key={paragraphIndex}>{renderInlineCode(paragraph)}</p>)}
        {item.bullets ? <ul>{item.bullets.map((bullet, bulletIndex) => <li key={bulletIndex}>{renderInlineCode(bullet)}</li>)}</ul> : null}
      </section>)}</div>
    </article>
  </main>
}
